/*
 * quants_metal.metal — Metal batch dequantization kernels.
 *
 * Line-for-line port of the device side of gpu/quants_gpu.cu, which is
 * itself bit-exact against the scalar reference in quants.c: each
 * thread dequantizes one element directly from the raw GGUF bytes that
 * were uploaded to device memory, using identical integer math (the
 * manual f16/bf16 bit manipulation, not MSL `half` conversions), so
 * GPU output is bit-for-bit comparable to gguf_dequant().
 *
 * The IQ importance grids / value tables live on the host in
 * quants.c; the host copies them into one device buffer (layout below)
 * at first use, replacing the __constant__ memory of the CUDA version.
 *
 * This file is embedded into the host binary as a string
 * (quants_metal_msl.h, generated by the Makefile) and compiled with
 * newLibraryWithSource() at first use.
 */

#include <metal_stdlib>
using namespace metal;

/* ================================================================
 * GGUF quant type codes — keep in sync with GGUFType in def.h
 * ================================================================ */

#define GGUF_TYPE_F32     0
#define GGUF_TYPE_F16     1
#define GGUF_TYPE_Q4_0    2
#define GGUF_TYPE_Q4_1    3
#define GGUF_TYPE_Q5_0    6
#define GGUF_TYPE_Q5_1    7
#define GGUF_TYPE_Q8_0    8
#define GGUF_TYPE_Q8_1    9
#define GGUF_TYPE_Q2_K    10
#define GGUF_TYPE_Q3_K    11
#define GGUF_TYPE_Q4_K    12
#define GGUF_TYPE_Q5_K    13
#define GGUF_TYPE_Q6_K    14
#define GGUF_TYPE_Q8_K    15
#define GGUF_TYPE_IQ2_XXS 16
#define GGUF_TYPE_IQ2_XS  17
#define GGUF_TYPE_IQ3_XXS 18
#define GGUF_TYPE_IQ1_S   19
#define GGUF_TYPE_IQ4_NL  20
#define GGUF_TYPE_IQ3_S   21
#define GGUF_TYPE_IQ2_S   22
#define GGUF_TYPE_IQ4_XS  23
#define GGUF_TYPE_I8      24
#define GGUF_TYPE_I16     25
#define GGUF_TYPE_I32     26
#define GGUF_TYPE_I64     27
#define GGUF_TYPE_F64     28
#define GGUF_TYPE_IQ1_M   29
#define GGUF_TYPE_BF16    30

/* ================================================================
 * Combined table buffer (float element offsets) — must match
 * metal_tables_init() in quants_metal.m: iq2_xxs (256), iq2_xs (512),
 * iq3_xxs (256), iq1_s (256), iq4_nl (256), iq3_s (512) floats.
 * ================================================================ */

#define IQ2_XXS_TAB 0
#define IQ2_XS_TAB  256
#define IQ3_XXS_TAB 768
#define IQ1_S_TAB   1024
#define IQ4_NL_TAB  1280
#define IQ3_S_TAB   1536

/* ================================================================
 * Params structs — layout must match the host definitions in
 * quants_metal.m (same field order and widths).
 * ================================================================ */

struct DequantParams {
    uint32_t type;
    uint64_t start_i;   /* block-aligned start (buffer begins here) */
    uint64_t i0;        /* first requested element                   */
    uint64_t nb;        /* element count                             */
};

struct MatmulParams {
    uint64_t rows;
    uint64_t cols;
    uint64_t batch;
};

/* ================================================================
 * Device helpers
 * ================================================================ */

/* Identical math to f16_to_f32() in quants.c / quants_gpu.cu. */
static inline float f16_to_f32(uint16_t bits) {
    uint32_t sign = (uint32_t)(bits >> 15) << 31;
    uint32_t exp  = (bits >> 10) & 0x1f;
    uint32_t mant = bits & 0x3ff;
    uint32_t f32;
    if (exp == 0) {
        if (mant == 0) {
            f32 = sign;
        } else {
            int e = 1 - 15;
            while ((mant & 0x400) == 0) { mant <<= 1; e--; }
            mant &= 0x3ff;
            f32 = sign | ((uint32_t)(e + 127) << 23) | (mant << 13);
        }
    } else if (exp == 31) {
        f32 = sign | (0xffu << 23) | (mant << 13); /* inf / nan */
    } else {
        f32 = sign | ((uint32_t)(exp - 15 + 127) << 23) | (mant << 13);
    }
    union { uint32_t u; float f; } v = { f32 };
    return v.f;
}

static inline float bf16_to_f32(uint16_t bits) {
    union { uint32_t u; float f; } v = { (uint32_t)bits << 16 };
    return v.f;
}

/* Alignment-safe multi-byte loads.  GGUF quant blocks start on odd byte
 * strides (e.g. q5_0 is 22 bytes), so a raw *(const uint32_t*) cast
 * could fault; assembling from bytes is correct for every alignment. */
static inline uint16_t ld_u16(device const uint8_t *p) {
    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);
}
static inline uint32_t ld_u32(device const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t ld_u64(device const uint8_t *p) {
    return (uint64_t)ld_u32(p) | ((uint64_t)ld_u32(p + 4) << 32);
}
static inline float ld_f32(device const uint8_t *p) {
    union { uint32_t u; float f; } v = { ld_u32(p) };
    return v.f;
}
static inline double ld_f64(device const uint8_t *p) {
    union { uint64_t u; double f; } v = { ld_u64(p) };
    return v.f;
}

static inline void q4k_scale_min(device const uint8_t *s, uint32_t sb, uint8_t *scale, uint8_t *min) {
    uint8_t d  = s[sb & 3];
    uint8_t m  = s[4 + (sb & 3)];
    uint8_t md = s[8 + (sb & 3)];
    if (sb < 4) {
        *scale = d & 0x3F;
        *min   = m & 0x3F;
    } else {
        *scale = (md & 0x0F) | ((d >> 2) & 0x30);
        *min   = (md >> 4) | ((m >> 2) & 0x30);
    }
}

/* ================================================================
 * Simple (non-block) types
 * ================================================================ */

static inline float dequant_F32(device const uint8_t *data, uint64_t i, device const float *tables) {
    return ld_f32(data + i * 4);
}
static inline float dequant_F16(device const uint8_t *data, uint64_t i, device const float *tables) {
    return f16_to_f32(ld_u16(data + i * 2));
}
static inline float dequant_BF16(device const uint8_t *data, uint64_t i, device const float *tables) {
    return bf16_to_f32(ld_u16(data + i * 2));
}
static inline float dequant_F64(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(ld_f64(data + i * 8));
}
static inline float dequant_I8(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int8_t)data[i];
}
static inline float dequant_I16(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int16_t)ld_u16(data + i * 2);
}
static inline float dequant_I32(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int32_t)ld_u32(data + i * 4);
}
static inline float dequant_I64(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int64_t)ld_u64(data + i * 8);
}

/* ================================================================
 * Simple block types (block_size = 32)
 * ================================================================ */

static inline float dequant_Q8_0(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 34;
    float d = f16_to_f32(ld_u16(blk));
    return (float)(int8_t)blk[2 + o] * d;
}

static inline float dequant_Q8_1(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 40;
    float d = ld_f32(blk);
    return (float)(int8_t)blk[8 + o] * d;
}

static inline float dequant_Q4_0(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 18;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t nib = (blk[2 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return ((float)(int32_t)nib - 8.0f) * d;
}

static inline float dequant_Q4_1(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 20;
    float d = f16_to_f32(ld_u16(blk));
    float m = f16_to_f32(ld_u16(blk + 2));
    uint32_t nib = (blk[4 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return (float)nib * d + m;
}

static inline float dequant_Q5_0(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 22;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t qh = ld_u32(blk + 2);
    uint32_t hi = (qh >> o) & 1;
    uint32_t lo = (blk[6 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return ((float)(int32_t)((hi << 4) | lo) - 16.0f) * d;
}

static inline float dequant_Q5_1(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 24;
    float d = f16_to_f32(ld_u16(blk));
    float m = f16_to_f32(ld_u16(blk + 2));
    uint32_t qh = ld_u32(blk + 4);
    uint32_t hi = (qh >> o) & 1;
    uint32_t lo = (blk[8 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return (float)((hi << 4) | lo) * d + m;
}

/* ================================================================
 * K-quant types (block_size = 256)
 * ================================================================ */

static inline float dequant_Q8_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 292;
    float d = ld_f32(blk);
    float bs = f16_to_f32(ld_u16(blk + 4 + 2 * (o >> 4)));
    return (float)(int8_t)blk[36 + o] * bs * d;
}

static inline float dequant_Q6_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 210;
    float d = f16_to_f32(ld_u16(blk + 208));
    int32_t sc = (int8_t)blk[192 + (o >> 4)];

    uint32_t hl      = o & 127;          /* position within 128-element half   */
    uint32_t which   = hl >> 5;          /* 0..3: which 32-element sub-group   */
    uint32_t l       = hl & 31;          /* 0..31: position inside sub-group   */
    uint32_t half    = o >> 7;           /* 0 or 1: which 128-element half     */

    uint32_t ql_off  = (half << 6) + ((which & 1) << 5) + l;
    uint32_t lo      = (which >= 2) ? ((blk[ql_off] >> 4) & 0xF)
                                    :  (blk[ql_off] & 0xF);

    uint32_t qh_off  = 128 + (half << 5) + l;
    uint32_t hi      = (blk[qh_off] >> (which * 2)) & 0x3;

    int32_t q  = (int32_t)(lo | (hi << 4)) - 32;
    return d * (float)sc * (float)q;
}

static inline float dequant_Q5_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 176;
    float d    = f16_to_f32(ld_u16(blk));
    float dmin = f16_to_f32(ld_u16(blk + 2));
    uint32_t sb = o >> 5;
    uint8_t sc, mn;
    q4k_scale_min(blk + 4, sb, &sc, &mn);
    uint32_t g  = o >> 6;
    uint32_t nb = (o >> 5) & 1;
    uint32_t bc = o & 31;
    uint32_t lo = (blk[48 + g * 32 + bc] >> (nb * 4)) & 0xF;
    uint32_t hi = (blk[16 + (o & 31)] >> (o >> 5)) & 1;
    int32_t q  = (int32_t)(lo | (hi << 4));
    return d * (float)sc * (float)q - dmin * (float)mn;
}

static inline float dequant_Q4_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 144;
    float d    = f16_to_f32(ld_u16(blk));
    float dmin = f16_to_f32(ld_u16(blk + 2));
    uint32_t sb = o >> 5;
    uint8_t sc, mn;
    q4k_scale_min(blk + 4, sb, &sc, &mn);
    uint32_t g  = o >> 6;
    uint32_t nb = (o >> 5) & 1;
    uint32_t bc = o & 31;
    uint32_t nib = (blk[16 + g * 32 + bc] >> (nb * 4)) & 0xF;
    return d * (float)sc * (float)nib - dmin * (float)mn;
}

static inline float dequant_Q3_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 110;
    float d = f16_to_f32(ld_u16(blk + 108));
    uint32_t s = o >> 4;
    uint32_t g  = o >> 7;
    uint32_t pr = (o >> 5) & 3;
    uint32_t bc = o & 31;
    uint32_t lo = (blk[32 + g * 32 + bc] >> (pr * 2)) & 3;
    uint32_t hi = (blk[o & 31] >> (o >> 5)) & 1;
    uint32_t sc_low  = (blk[96 + (s & 7)]  >> (s >= 8 ? 4 : 0)) & 0xF;
    uint32_t sc_high = (blk[104 + (s & 3)] >> ((s >> 2) * 2)) & 0x3;
    int32_t sc = (int32_t)(sc_low | (sc_high << 4)) - 32;
    int32_t q  = (int32_t)(lo | (hi << 2)) - 4;
    return d * (float)sc * (float)q;
}

static inline float dequant_Q2_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 84;
    float d  = f16_to_f32(ld_u16(blk + 64 + 16));
    float mn = f16_to_f32(ld_u16(blk + 64 + 16 + 2));
    uint32_t sb  = o >> 4;
    uint32_t sc  = blk[64 + (sb >> 1)];
    if (sb & 1) sc >>= 4; else sc &= 0xF;
    uint32_t q2 = (blk[(o >> 2)] >> ((o & 3) << 1)) & 0x3;
    int32_t q  = (int32_t)q2 - (int32_t)((blk[(o >> 3)] >> (o & 7)) & 1) * 4;
    float sc_f = (float)(int32_t)sc;
    return d * sc_f * (float)q - mn;
}

/* ================================================================
 * IQ (importance-matrix-aware) types
 * ================================================================ */

static inline float dequant_IQ2_XXS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 66;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t q = (blk[2 + (o >> 2)] >> ((o & 3) << 1)) & 0x3;
    uint32_t sign_bit = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    float v = tables[IQ2_XXS_TAB + (q | (sign_bit << 2))];
    return v * d;
}

static inline float dequant_IQ2_XS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 74;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t sh = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t q  = (blk[2 + 32 + (o >> 2)] >> ((o & 3) << 1)) & 0x3;
    uint32_t idx = q | (sh << 2);
    int8_t  sc = (int8_t)(blk[2 + 32 + 64 + (o >> 4)]);
    return d * (float)sc * tables[IQ2_XS_TAB + idx];
}

static inline float dequant_IQ3_XXS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 98;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t qh = (blk[2 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t qm = (blk[2 + 8 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t ql = (blk[2 + 8 + 32 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t grp = (blk[2 + 8 + 32 + 128 + (o >> 3)] >> ((o & 7) << 1)) & 0x3;
    uint32_t idx = ql | (qm << 4) | (qh << 5) | (grp << 6);
    int8_t  sc  = (int8_t)(blk[2 + 8 + 32 + 128 + 64 + (o >> 4)]);
    return d * (float)sc * tables[IQ3_XXS_TAB + idx];
}

static inline float dequant_IQ1_S(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 110;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t q  = ((blk[2 + (o >> 3)] >> (o & 7)) & 1) |
                  (((blk[2 + 32 + (o >> 3)] >> (o & 7)) & 1) << 1);
    uint32_t idx = q | (((o >> 4) & 0xF) << 2);
    return d * tables[IQ1_S_TAB + idx];
}

static inline float dequant_IQ4_NL(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 50;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t q = (blk[2 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return d * tables[IQ4_NL_TAB + (q | ((o & 0xF) << 4))];
}

static inline float dequant_IQ1_M(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 56;
    float d = f16_to_f32(ld_u16(blk + 54));
    uint32_t sb    = o >> 4;
    uint32_t sc    = (blk[sb >> 1] >> ((sb & 1) << 2)) & 0xF;
    float sc_f = (float)(int32_t)sc + 1.0f;
    uint32_t val  = (blk[8 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t sign = (blk[8 + 32 + (o >> 3)] >> (o & 7)) & 1;
    float v = sign ? -(float)val : (float)val;
    return v * sc_f * d;
}

static inline float dequant_IQ3_S(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 110;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t sign = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t qh   = (blk[2 + 32 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t qm   = (blk[2 + 32 + 8 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t ql   = (blk[2 + 32 + 8 + 32 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t idx  = ql | (qm << 4) | (qh << 5) | (sign << 6);
    int8_t  sc   = (int8_t)blk[2 + 32 + 8 + 32 + 128 + (o >> 4)];
    return d * (float)sc * tables[IQ3_S_TAB + idx];
}

static inline float dequant_IQ2_S(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 82;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t sign = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t qh   = (blk[2 + 32 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t ql   = (blk[2 + 32 + 8 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t idx  = ql | (qh << 4) | (sign << 5);
    int8_t  sc   = (int8_t)blk[2 + 32 + 8 + 128 + (o >> 4) + ((o >> 4) & 1) * 16];
    uint32_t sc_l = (blk[2 + 32 + 8 + 128 + (o >> 5)] >> ((o & 31) >> 2)) & 0x3;
    float sc_f = (float)sc + 0.125f * (float)(int32_t)sc_l;
    return d * sc_f * tables[IQ2_XS_TAB + idx];
}

static inline float dequant_IQ4_XS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 136;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t qh = (blk[2 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t ql = (blk[2 + 8 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t q  = ql | (qh << 4);
    int8_t  sc_l = (int8_t)blk[2 + 8 + 128 + (o >> 4)];
    int8_t  sc_h = (int8_t)blk[2 + 8 + 128 + 16 + (o >> 4)];
    float sc = (float)(int32_t)sc_l + ((float)(int32_t)sc_h / 127.0f);
    return d * sc * tables[IQ4_NL_TAB + q];
}

/* ================================================================
 * Runtime-switch dispatcher (dequant / dot kernels only; the matmul
 * kernels below are compile-time specialized per type).
 * ================================================================ */

static inline float dequant_one(uint32_t type, device const uint8_t *data, uint64_t i, device const float *tables) {
    switch (type) {
        case GGUF_TYPE_F32:     return dequant_F32(data, i, tables);
        case GGUF_TYPE_F16:     return dequant_F16(data, i, tables);
        case GGUF_TYPE_BF16:    return dequant_BF16(data, i, tables);
        case GGUF_TYPE_F64:     return dequant_F64(data, i, tables);
        case GGUF_TYPE_I8:      return dequant_I8(data, i, tables);
        case GGUF_TYPE_I16:     return dequant_I16(data, i, tables);
        case GGUF_TYPE_I32:     return dequant_I32(data, i, tables);
        case GGUF_TYPE_I64:     return dequant_I64(data, i, tables);
        case GGUF_TYPE_Q8_0:    return dequant_Q8_0(data, i, tables);
        case GGUF_TYPE_Q8_1:    return dequant_Q8_1(data, i, tables);
        case GGUF_TYPE_Q4_0:    return dequant_Q4_0(data, i, tables);
        case GGUF_TYPE_Q4_1:    return dequant_Q4_1(data, i, tables);
        case GGUF_TYPE_Q5_0:    return dequant_Q5_0(data, i, tables);
        case GGUF_TYPE_Q5_1:    return dequant_Q5_1(data, i, tables);
        case GGUF_TYPE_Q8_K:    return dequant_Q8_K(data, i, tables);
        case GGUF_TYPE_Q6_K:    return dequant_Q6_K(data, i, tables);
        case GGUF_TYPE_Q5_K:    return dequant_Q5_K(data, i, tables);
        case GGUF_TYPE_Q4_K:    return dequant_Q4_K(data, i, tables);
        case GGUF_TYPE_Q3_K:    return dequant_Q3_K(data, i, tables);
        case GGUF_TYPE_Q2_K:    return dequant_Q2_K(data, i, tables);
        case GGUF_TYPE_IQ2_XXS: return dequant_IQ2_XXS(data, i, tables);
        case GGUF_TYPE_IQ2_XS:  return dequant_IQ2_XS(data, i, tables);
        case GGUF_TYPE_IQ3_XXS: return dequant_IQ3_XXS(data, i, tables);
        case GGUF_TYPE_IQ1_S:   return dequant_IQ1_S(data, i, tables);
        case GGUF_TYPE_IQ4_NL:  return dequant_IQ4_NL(data, i, tables);
        case GGUF_TYPE_IQ1_M:   return dequant_IQ1_M(data, i, tables);
        case GGUF_TYPE_IQ3_S:   return dequant_IQ3_S(data, i, tables);
        case GGUF_TYPE_IQ2_S:   return dequant_IQ2_S(data, i, tables);
        case GGUF_TYPE_IQ4_XS:  return dequant_IQ4_XS(data, i, tables);
        default:                return 0.0f;
    }
}

/* ================================================================
 * Kernels
 * ================================================================ */

/* Dequantize elements [i0, i0+nb) into out.  data points at the start
 * of the block containing element start_i (start_i is block-aligned),
 * so a thread dequantizes relative element (i0 + j) - start_i. */
kernel void dequant_range(device const uint8_t *data [[buffer(0)]],
                          device float *out [[buffer(1)]],
                          device const float *tables [[buffer(2)]],
                          constant struct DequantParams &p [[buffer(3)]],
                          uint tid [[thread_position_in_grid]],
                          uint tptg [[threads_per_threadgroup]],
                          uint ntg  [[threadgroups_per_grid]]) {
    uint64_t idx    = (uint64_t)tid;
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t j = idx; j < p.nb; j += stride) {
        out[j] = dequant_one(p.type, data, (p.i0 + j) - p.start_i, tables);
    }
}

/* Fused dequant + dot: sum_{j=0}^{n-1} w[i0+j] * x[j], one partial sum
 * per threadgroup, host-side final reduction. */
kernel void dequant_dot(device const uint8_t *data [[buffer(0)]],
                        device const float *x [[buffer(1)]],
                        device float *partial [[buffer(2)]],
                        device const float *tables [[buffer(3)]],
                        constant struct DequantParams &p [[buffer(4)]],
                        uint tid [[thread_position_in_threadgroup]],
                        uint tptg [[threads_per_threadgroup]],
                        uint idx [[thread_position_in_grid]],
                        uint tg  [[threadgroup_position_in_grid]],
                        uint ntg [[threadgroups_per_grid]]) {
    threadgroup float sh[256];
    uint64_t stride = (uint64_t)ntg * tptg;
    float sum = 0.0f;
    for (uint64_t j = idx; j < p.nb; j += stride) {
        sum += dequant_one(p.type, data, (p.i0 + j) - p.start_i, tables) * x[j];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint s = tptg >> 1; s > 0; s >>= 1) {
        if (tid < s) sh[tid] += sh[tid + s];
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (tid == 0) partial[tg] = sh[0];
}

/* ================================================================
 * Persistent-weight matmul kernels
 *
 * w points at the device copy of the whole tensor; all indices are
 * FLAT element indices (i = r*cols + c / c*rows + r), identical to
 * the scalar reference gguf_dequant().  GGUF quantized tensors have
 * no per-row padding — block boundaries may fall mid-row — so the
 * dequant helpers must derive the block from the flat index, never
 * from a precomputed row pointer.
 *
 * Each type is instantiated as its own kernel via the X-macro below
 * (the MSL analogue of the CUDA template instantiations), so the
 * per-element decode is straight-line code in the inner loop.
 * ================================================================ */

#define METAL_TYPE_LIST(X) \
    X(F32) X(F16) X(Q4_0) X(Q4_1) \
    X(Q5_0) X(Q5_1) X(Q8_0) X(Q8_1) \
    X(Q2_K) X(Q3_K) X(Q4_K) X(Q5_K) \
    X(Q6_K) X(Q8_K) X(IQ2_XXS) X(IQ2_XS) \
    X(IQ3_XXS) X(IQ1_S) X(IQ4_NL) X(IQ3_S) \
    X(IQ2_S) X(IQ4_XS) X(I8) X(I16) \
    X(I32) X(I64) X(F64) X(IQ1_M) \
    X(BF16)

/* Non-transposed: y[b*rows + r] = sum_c w[r*cols + c] * x[b*cols + c].
 * One SIMD group (warp) per output row; lanes stride c by 32 so each
 * iteration covers exactly one quant block (QK=32 types) — coalesced
 * loads.  simd_sum() replaces the CUDA shuffle-tree reduction; the
 * accumulation order may differ, which the tolerant matmul checks
 * allow for.  Grid = (ceil(rows/8), batch); r is SIMD-group-uniform so
 * the bounds check exits whole groups. */
#define DEFINE_MATMUL_NT(T)                                                            \
kernel void matmul_nt_##T(device const uint8_t *w [[buffer(0)]],                       \
                          device const float *x [[buffer(1)]],                         \
                          device float *y [[buffer(2)]],                               \
                          device const float *tables [[buffer(3)]],                    \
                          constant struct MatmulParams &p [[buffer(4)]],               \
                          uint tid [[thread_position_in_threadgroup]],                 \
                          uint2 tg [[threadgroup_position_in_grid]]) {                 \
    uint simd = tid >> 5;                                                              \
    uint lane = tid & 31;                                                              \
    uint64_t r = (uint64_t)tg.x * 8 + simd;                                            \
    if (r >= p.rows) return;                                                           \
    device const float *xr = x + (uint64_t)tg.y * p.cols;                              \
    float sum = 0.0f;                                                                  \
    for (uint64_t c = lane; c < p.cols; c += 32)                                       \
        sum += dequant_##T(w, r * p.cols + c, tables) * xr[c];                         \
    float total = simd_sum(sum);                                                       \
    if (lane == 0) y[(uint64_t)tg.y * p.rows + r] = total;                             \
}
METAL_TYPE_LIST(DEFINE_MATMUL_NT)
#undef DEFINE_MATMUL_NT

/* Transposed: y[b*rows + idx] = sum_c w[c*rows + idx] * x[b*cols + c].
 * One thread per output element; 256 threads cover 256 outputs, so
 * per c the 32 lanes of a SIMD group read the same quant block (QK=32
 * types: block headers broadcast, elements gathered within the
 * block). */
#define DEFINE_MATMUL_T(T)                                                             \
kernel void matmul_t_##T(device const uint8_t *w [[buffer(0)]],                        \
                         device const float *x [[buffer(1)]],                          \
                         device float *y [[buffer(2)]],                                \
                         device const float *tables [[buffer(3)]],                     \
                         constant struct MatmulParams &p [[buffer(4)]],                \
                         uint tid [[thread_position_in_threadgroup]],                  \
                         uint tptg [[threads_per_threadgroup]],                        \
                         uint2 tg [[threadgroup_position_in_grid]]) {                  \
    uint64_t idx = (uint64_t)tg.x * tptg + tid;                                        \
    if (idx >= p.rows) return;                                                         \
    device const float *xr = x + (uint64_t)tg.y * p.cols;                              \
    float sum = 0.0f;                                                                  \
    for (uint64_t c = 0; c < p.cols; c++)                                              \
        sum += dequant_##T(w, c * p.rows + idx, tables) * xr[c];                       \
    y[(uint64_t)tg.y * p.rows + idx] = sum;                                            \
}
METAL_TYPE_LIST(DEFINE_MATMUL_T)
#undef DEFINE_MATMUL_T
