/*
 * metal.m — Metal batch dequantization backend (macOS only).
 *
 * Objective-C host side of the Metal GPU backend; the kernels live in
 * metal.metal and are embedded here via metal_msl.h
 * (generated by the Makefile), then compiled at first use with
 * newLibraryWithSource().
 *
 * The API mirrors backend/gpu/gpu.cu exactly: every wrapper falls back
 * to the scalar gguf_dequant() CPU path when no usable Metal device is
 * present, a quant type is unsupported, or a device buffer cannot be
 * allocated, so callers use the same API unconditionally.  Hard device
 * errors (kernel library / pipeline compile failure, command buffer
 * failure) are fatal, matching CHECK() in the CUDA backend.
 *
 * Metal command buffers are not thread-safe, so every entry point is
 * serialized through a global mutex (the CUDA backend does not need
 * this).
 */

#import <Metal/Metal.h>
#import <Foundation/Foundation.h>

#include <pthread.h>
#include <stdlib.h>
#include <string.h>

#include "../../def.h"
#include "metal.h"
#include "metal_msl.h" /* metal_msl[] — embedded kernel source */

/* Scalar reference dequant, used only by the CPU fallback paths. */
float gguf_dequant(TensorInfo *ti, u64 i);

/* IQ grids / value tables defined in quants.c, concatenated into one
 * device buffer at first use (see metal.metal for the layout). */
extern const float iq2_xxs_grid[];
extern const float iq2_xs_grid[];
extern const float iq3_xxs_grid[];
extern const float iq1_s_grid[];
extern const float iq4_nl_values[];
extern const float iq3_s_grid[];

/* ================================================================
 * Device state (all guarded by g_lock)
 * ================================================================ */

#define IQ2_XXS_SIZE 256
#define IQ2_XS_SIZE  512
#define IQ3_XXS_SIZE 256
#define IQ1_S_SIZE   256
#define IQ4_NL_SIZE  256
#define IQ3_S_SIZE   512
#define IQ_TABLES_SIZE (IQ2_XXS_SIZE + IQ2_XS_SIZE + IQ3_XXS_SIZE + \
                        IQ1_S_SIZE + IQ4_NL_SIZE + IQ3_S_SIZE)

static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER;
static id<MTLDevice> g_device;
static id<MTLCommandQueue> g_queue;
static id<MTLLibrary> g_library;
static id<MTLBuffer> g_tables; /* concatenated IQ grids / value tables */
static id<MTLComputePipelineState> g_pipe_dequant;
static id<MTLComputePipelineState> g_pipe_dot;
static id<MTLComputePipelineState> g_pipes[31][2]; /* [type][trans] */

/* Params structs — layout must match the structs in metal.metal. */
typedef struct {
    u32  type;
    u64  start_i; /* block-aligned start (buffer begins here) */
    u64  i0;      /* first requested element                   */
    u64  nb;      /* element count                             */
} MetalDequantParams;

typedef struct {
    u64 rows;
    u64 cols;
    u64 batch;
} MetalMatmulParams;

/* Kernel-function suffix per GGUF type — NULL slots (types 4/5 do not
 * exist) mean "fall back to CPU".  Must match METAL_TYPE_LIST in
 * metal.metal, which names the kernels matmul_nt_<T>/matmul_t_<T>. */
static const char *metal_type_suffix[31] = {
    "F32", "F16", "Q4_0", "Q4_1", NULL, NULL, "Q5_0", "Q5_1",
    "Q8_0", "Q8_1", "Q2_K", "Q3_K", "Q4_K", "Q5_K", "Q6_K", "Q8_K",
    "IQ2_XXS", "IQ2_XS", "IQ3_XXS", "IQ1_S", "IQ4_NL", "IQ3_S",
    "IQ2_S", "IQ4_XS", "I8", "I16", "I32", "I64", "F64", "IQ1_M", "BF16"
};

/* ================================================================
 * Geometry / dispatch helpers
 * ================================================================ */

/* Block geometry per GGUF type — must match gguf_types[] in core.c
 * and gpu_geom() in gpu.cu. */
static int metal_geom(u32 type, u64 *block_elems, u64 *block_bytes) {
    switch (type) {
        case GGUF_TYPE_F32:     *block_elems = 1;   *block_bytes = 4;   return 0;
        case GGUF_TYPE_F16:     *block_elems = 1;   *block_bytes = 2;   return 0;
        case GGUF_TYPE_BF16:    *block_elems = 1;   *block_bytes = 2;   return 0;
        case GGUF_TYPE_F64:     *block_elems = 1;   *block_bytes = 8;   return 0;
        case GGUF_TYPE_I8:      *block_elems = 1;   *block_bytes = 1;   return 0;
        case GGUF_TYPE_I16:     *block_elems = 1;   *block_bytes = 2;   return 0;
        case GGUF_TYPE_I32:     *block_elems = 1;   *block_bytes = 4;   return 0;
        case GGUF_TYPE_I64:     *block_elems = 1;   *block_bytes = 8;   return 0;
        case GGUF_TYPE_Q4_0:    *block_elems = 32;  *block_bytes = 18;  return 0;
        case GGUF_TYPE_Q4_1:    *block_elems = 32;  *block_bytes = 20;  return 0;
        case GGUF_TYPE_Q5_0:    *block_elems = 32;  *block_bytes = 22;  return 0;
        case GGUF_TYPE_Q5_1:    *block_elems = 32;  *block_bytes = 24;  return 0;
        case GGUF_TYPE_Q8_0:    *block_elems = 32;  *block_bytes = 34;  return 0;
        case GGUF_TYPE_Q8_1:    *block_elems = 32;  *block_bytes = 40;  return 0;
        case GGUF_TYPE_Q2_K:    *block_elems = 256; *block_bytes = 84;  return 0;
        case GGUF_TYPE_Q3_K:    *block_elems = 256; *block_bytes = 110; return 0;
        case GGUF_TYPE_Q4_K:    *block_elems = 256; *block_bytes = 144; return 0;
        case GGUF_TYPE_Q5_K:    *block_elems = 256; *block_bytes = 176; return 0;
        case GGUF_TYPE_Q6_K:    *block_elems = 256; *block_bytes = 210; return 0;
        case GGUF_TYPE_Q8_K:    *block_elems = 256; *block_bytes = 292; return 0;
        case GGUF_TYPE_IQ2_XXS: *block_elems = 256; *block_bytes = 66;  return 0;
        case GGUF_TYPE_IQ2_XS:  *block_elems = 256; *block_bytes = 74;  return 0;
        case GGUF_TYPE_IQ3_XXS: *block_elems = 256; *block_bytes = 98;  return 0;
        case GGUF_TYPE_IQ1_S:   *block_elems = 256; *block_bytes = 110; return 0;
        case GGUF_TYPE_IQ4_NL:  *block_elems = 256; *block_bytes = 50;  return 0;
        case GGUF_TYPE_IQ3_S:   *block_elems = 256; *block_bytes = 110; return 0;
        case GGUF_TYPE_IQ2_S:   *block_elems = 256; *block_bytes = 82;  return 0;
        case GGUF_TYPE_IQ4_XS:  *block_elems = 256; *block_bytes = 136; return 0;
        case GGUF_TYPE_IQ1_M:   *block_elems = 256; *block_bytes = 56;  return 0;
        default: return -1;
    }
}

#define METAL_THREADS   256
#define METAL_MAX_BLOCKS 65535u

static inline unsigned metal_block_count(u64 n) {
    u64 want = (n + METAL_THREADS - 1) / METAL_THREADS;
    return (unsigned)(want < METAL_MAX_BLOCKS ? want : METAL_MAX_BLOCKS);
}

/* ================================================================
 * Init / teardown
 * ================================================================ */

int metal_available(void) {
    static int cached = -1; /* memoized: checked on every matmul call */
    if (cached >= 0) return cached;
    pthread_mutex_lock(&g_lock);
    if (!g_device) g_device = MTLCreateSystemDefaultDevice();
    cached = g_device ? 1 : 0;
    pthread_mutex_unlock(&g_lock);
    return cached;
}

/* Upload the IQ grids / value tables from quants.c into one device
 * buffer.  Layout (float offsets) must match the _TAB defines in
 * metal.metal. */
static void metal_tables_init(void) {
    float tables[IQ_TABLES_SIZE];
    memcpy(tables + 0, iq2_xxs_grid, IQ2_XXS_SIZE * sizeof(float));
    memcpy(tables + IQ2_XXS_SIZE, iq2_xs_grid, IQ2_XS_SIZE * sizeof(float));
    memcpy(tables + IQ2_XXS_SIZE + IQ2_XS_SIZE, iq3_xxs_grid, IQ3_XXS_SIZE * sizeof(float));
    memcpy(tables + IQ2_XXS_SIZE + IQ2_XS_SIZE + IQ3_XXS_SIZE, iq1_s_grid, IQ1_S_SIZE * sizeof(float));
    memcpy(tables + IQ2_XXS_SIZE + IQ2_XS_SIZE + IQ3_XXS_SIZE + IQ1_S_SIZE, iq4_nl_values, IQ4_NL_SIZE * sizeof(float));
    memcpy(tables + IQ2_XXS_SIZE + IQ2_XS_SIZE + IQ3_XXS_SIZE + IQ1_S_SIZE + IQ4_NL_SIZE, iq3_s_grid, IQ3_S_SIZE * sizeof(float));
    g_tables = [g_device newBufferWithBytes:tables length:sizeof(tables) options:MTLResourceStorageModeShared];
}

/* Create the device, queue, table buffer, and compile the embedded
 * kernel library.  Returns 0 when ready, -1 when the device/queue/
 * table buffer is unavailable (caller falls back to CPU).  Library or
 * pipeline compile failure is fatal, matching CHECK() in the CUDA
 * backend.  Must be called with g_lock held. */
static int metal_ensure_ready(void) {
    if (!g_device) {
        g_device = MTLCreateSystemDefaultDevice();
        if (!g_device) return -1;
    }
    if (!g_queue) {
        g_queue = [g_device newCommandQueue];
        if (!g_queue) return -1;
    }
    if (!g_tables) {
        metal_tables_init();
        if (!g_tables) return -1;
    }
    if (!g_library) {
        MTLCompileOptions *opts = [MTLCompileOptions new];
        opts.languageVersion = MTLLanguageVersion2_0;
        /* Disable fast math: it may contract/reassociate float ops,
         * which would break bit-exact parity with gguf_dequant(). */
        opts.fastMathEnabled = NO;
        NSError *err = nil;
        g_library = [g_device newLibraryWithSource:[NSString stringWithUTF8String:metal_msl]
                                           options:opts error:&err];
        if (!g_library) {
            fprintf(stderr, "Error: %s: %d: Metal library compile failed: %s\n",
                    __FILE__, __LINE__, err ? err.localizedDescription.UTF8String : "unknown");
            exit(1);
        }
    }
    return 0;
}

static id<MTLComputePipelineState> metal_pipeline_for(NSString *name) {
    NSError *err = nil;
    id<MTLFunction> fn = [g_library newFunctionWithName:name];
    if (!fn) {
        fprintf(stderr, "Error: %s: %d: Metal function %s not found\n",
                __FILE__, __LINE__, name.UTF8String);
        exit(1);
    }
    id<MTLComputePipelineState> pipe = [g_device newComputePipelineStateWithFunction:fn error:&err];
    if (!pipe) {
        fprintf(stderr, "Error: %s: %d: Metal pipeline: %s\n",
                __FILE__, __LINE__, err ? err.localizedDescription.UTF8String : "unknown");
        exit(1);
    }
    return pipe;
}

static id<MTLComputePipelineState> metal_matmul_pipeline(u32 type, bool trans) {
    id<MTLComputePipelineState> pipe = g_pipes[type][trans];
    if (pipe) return pipe;
    pipe = metal_pipeline_for([NSString stringWithFormat:@"matmul_%@_%s",
                               trans ? @"t" : @"nt", metal_type_suffix[type]]);
    g_pipes[type][trans] = pipe;
    return pipe;
}

/* Dispatch one kernel and wait.  b4 may be nil (kernels that do not
 * declare buffer(4)).  A failed command buffer is fatal. */
static void metal_execute(id<MTLComputePipelineState> pipe, MTLSize grid, MTLSize tptg,
                          id<MTLBuffer> b0, id<MTLBuffer> b1, id<MTLBuffer> b2,
                          id<MTLBuffer> b3, id<MTLBuffer> b4) {
    @autoreleasepool {
        id<MTLCommandBuffer> cb = [g_queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
        [enc setComputePipelineState:pipe];
        [enc setBuffer:b0 atIndex:0];
        [enc setBuffer:b1 atIndex:1];
        [enc setBuffer:b2 atIndex:2];
        [enc setBuffer:b3 atIndex:3];
        if (b4) [enc setBuffer:b4 atIndex:4];
        [enc dispatchThreadgroups:grid threadsPerThreadgroup:tptg];
        [enc endEncoding];
        [cb commit];
        [cb waitUntilCompleted];
        if (cb.status == MTLCommandBufferStatusError) {
            fprintf(stderr, "Error: %s: %d: Metal command buffer: %s\n",
                    __FILE__, __LINE__,
                    cb.error ? cb.error.localizedDescription.UTF8String : "unknown");
            exit(1);
        }
    }
}

/* ================================================================
 * Scalar CPU fallbacks
 * ================================================================ */

static void scalar_dequant_range(TensorInfo *ti,
                                 u64 i0, u64 nb, float *out) {
    for (u64 j = 0; j < nb; j++)
        out[j] = gguf_dequant(ti, i0 + j);
}

static float scalar_dot(TensorInfo *ti,
                        u64 i, u64 n, const float *x) {
    double sum = 0.0;
    for (u64 j = 0; j < n; j++)
        sum += (double)gguf_dequant(ti, i + j) * (double)x[j];
    return (float)sum;
}

/* ================================================================
 * Dequant / dot batch
 * ================================================================ */

static int metal_dequant_batch_inner(TensorInfo *ti,
                                     u64 i0, u64 nb, float *out) {
    if (metal_ensure_ready() != 0) {
        scalar_dequant_range(ti, i0, nb, out);
        return 0;
    }

    u64 be, bb;
    if (metal_geom(ti->type, &be, &bb) != 0) {
        scalar_dequant_range(ti, i0, nb, out);
        return 0;
    }

    u64 start_i  = (i0 / be) * be;
    u64 end_i    = i0 + nb;
    u64 n_blocks = (end_i - start_i + be - 1) / be;
    u64 bytes    = n_blocks * bb;
    const u8 *src = (const u8 *)ti->data + (start_i / be) * bb;
    /* Copy through the tensor's declared end, not just the decoded
     * blocks: some IQ decoders read a few bytes past the last block
     * (block-relative offsets spilling beyond the block end), so the
     * device buffer must include the tensor's tail to keep those reads
     * deterministic.  The unit-test tensors carry a padding tail inside
     * ti->bytes; production tensors have ti->bytes == n_blocks*bb, so
     * this is a no-op there. */
    bytes = ti->bytes - (start_i / be) * bb;
    if (bytes > (u64)g_device.maxBufferLength) {
        scalar_dequant_range(ti, i0, nb, out);
        return 0;
    }

    id<MTLBuffer> d_data = [g_device newBufferWithBytes:src length:(NSUInteger)bytes options:MTLResourceStorageModeShared];
    id<MTLBuffer> d_out  = [g_device newBufferWithLength:(NSUInteger)(nb * sizeof(float)) options:MTLResourceStorageModeShared];
    if (!d_data || !d_out) {
        scalar_dequant_range(ti, i0, nb, out);
        return 0;
    }

    struct MetalDequantParams dp = { ti->type, start_i, i0, nb };
    id<MTLBuffer> d_p = [g_device newBufferWithBytes:&dp length:sizeof(dp) options:MTLResourceStorageModeShared];

    if (!g_pipe_dequant) g_pipe_dequant = metal_pipeline_for(@"dequant_range");
    MTLSize tptg = MTLSizeMake(METAL_THREADS, 1, 1);
    MTLSize grid = MTLSizeMake(metal_block_count(nb), 1, 1);
    metal_execute(g_pipe_dequant, grid, tptg, d_data, d_out, g_tables, d_p, nil);

    memcpy(out, d_out.contents, (size_t)(nb * sizeof(float)));
    return 0;
}

int metal_dequant_batch(TensorInfo *ti, u64 i0, u64 nb, float *out) {
    if (!ti || !ti->data || !out || nb == 0) return 0;
    if (i0 + nb > ti->n_element) return -1;

    pthread_mutex_lock(&g_lock);
    @autoreleasepool {
        int rc = metal_dequant_batch_inner(ti, i0, nb, out);
        pthread_mutex_unlock(&g_lock);
        return rc;
    }
}

int metal_dequant_tensor(TensorInfo *ti, float *out) {
    if (!ti || !ti->data || !out) return -1;

    pthread_mutex_lock(&g_lock);
    @autoreleasepool {
        int rc = metal_dequant_batch_inner(ti, 0, ti->n_element, out);
        pthread_mutex_unlock(&g_lock);
        return rc;
    }
}

static float metal_dot_batch_inner(TensorInfo *ti,
                                   u64 i, u64 n, const float *x) {
    if (metal_ensure_ready() != 0)
        return scalar_dot(ti, i, n, x);

    u64 be, bb;
    if (metal_geom(ti->type, &be, &bb) != 0)
        return scalar_dot(ti, i, n, x);

    u64 start_i  = (i / be) * be;
    u64 end_i    = i + n;
    u64 n_blocks = (end_i - start_i + be - 1) / be;
    u64 bytes    = n_blocks * bb;
    const u8 *src = (const u8 *)ti->data + (start_i / be) * bb;
    if (bytes > (u64)g_device.maxBufferLength)
        return scalar_dot(ti, i, n, x);

    unsigned blocks = metal_block_count(n);
    id<MTLBuffer> d_data = [g_device newBufferWithBytes:src length:(NSUInteger)bytes options:MTLResourceStorageModeShared];
    id<MTLBuffer> d_x    = [g_device newBufferWithBytes:x length:(NSUInteger)(n * sizeof(float)) options:MTLResourceStorageModeShared];
    id<MTLBuffer> d_partial = [g_device newBufferWithLength:(NSUInteger)(blocks * sizeof(float)) options:MTLResourceStorageModeShared];
    if (!d_data || !d_x || !d_partial)
        return scalar_dot(ti, i, n, x);

    struct MetalDequantParams dp = { ti->type, start_i, i, n };
    id<MTLBuffer> d_p = [g_device newBufferWithBytes:&dp length:sizeof(dp) options:MTLResourceStorageModeShared];

    if (!g_pipe_dot) g_pipe_dot = metal_pipeline_for(@"dequant_dot");
    MTLSize tptg = MTLSizeMake(METAL_THREADS, 1, 1);
    MTLSize grid = MTLSizeMake(blocks, 1, 1);
    metal_execute(g_pipe_dot, grid, tptg, d_data, d_x, d_partial, g_tables, d_p);

    const float *partial = (const float *)d_partial.contents;
    double sum = 0.0;
    for (unsigned b = 0; b < blocks; b++)
        sum += (double)partial[b];
    return (float)sum;
}

float metal_dot_batch(TensorInfo *ti, u64 i, u64 n, const float *x) {
    if (!ti || !ti->data || !x || n == 0) return 0.0f;
    if (i + n > ti->n_element) return 0.0f;

    pthread_mutex_lock(&g_lock);
    @autoreleasepool {
        float v = metal_dot_batch_inner(ti, i, n, x);
        pthread_mutex_unlock(&g_lock);
        return v;
    }
}

/* ================================================================
 * Persistent-weight matmul backend
 * ================================================================ */

/* Device weight cache: (ti->data, ti) identifies a tensor
 * unambiguously (ti->data is the resolved host buffer; ti the flat
 * tensor array element).  Uploaded lazily on first use; never evicted —
 * weights are read-only and the model is loaded once.  A failed
 * upload is a CPU fallback, not fatal.
 *
 * A content snapshot guards the pointer key: if a caller reuses a
 * freed (ti->data, ti) identity for a new tensor (the unit tests hit
 * this via malloc address reuse), the stale device copy is replaced rather
 * than served.  The engine never aliases identities, so the snapshot
 * always matches there and the replace path is never taken. */
#define METAL_CACHE_MAX 4096
static const u8      *g_cache_base[METAL_CACHE_MAX];
static TensorInfo    *g_cache_ti[METAL_CACHE_MAX];
static id<MTLBuffer>  g_cache_dev[METAL_CACHE_MAX];
static u64            g_cache_elems[METAL_CACHE_MAX];
static u64            g_cache_bytes[METAL_CACHE_MAX];
static u32            g_cache_type[METAL_CACHE_MAX];
static u64            g_cache_off[METAL_CACHE_MAX];
static int            g_cache_n = 0;

static id<MTLBuffer> metal_cache_upload(TensorInfo *ti) {
    if ((u64)ti->bytes > (u64)g_device.maxBufferLength) return nil;
    return [g_device newBufferWithBytes:ti->data length:(NSUInteger)ti->bytes
                                options:MTLResourceStorageModeShared];
}

static id<MTLBuffer> metal_cache_get(TensorInfo *ti) {
    for (int i = 0; i < g_cache_n; i++) {
        if (g_cache_base[i] != ti->data || g_cache_ti[i] != ti) continue;
        if (g_cache_elems[i] == ti->n_element && g_cache_bytes[i] == ti->bytes &&
            g_cache_type[i] == ti->type && g_cache_off[i] == ti->offset)
            return g_cache_dev[i]; /* same identity, same content */
        /* Same pointers, different content: replace the dead copy. */
        g_cache_dev[i] = nil;
        id<MTLBuffer> d = metal_cache_upload(ti);
        if (!d) return nil;
        g_cache_dev[i]   = d;
        g_cache_elems[i] = ti->n_element;
        g_cache_bytes[i] = ti->bytes;
        g_cache_type[i]  = ti->type;
        g_cache_off[i]   = ti->offset;
        return d;
    }
    if (g_cache_n >= METAL_CACHE_MAX || ti->bytes == 0) return nil;
    id<MTLBuffer> d = metal_cache_upload(ti);
    if (!d) return nil;
    g_cache_base[g_cache_n] = ti->data;
    g_cache_ti[g_cache_n]   = ti;
    g_cache_dev[g_cache_n]  = d;
    g_cache_elems[g_cache_n] = ti->n_element;
    g_cache_bytes[g_cache_n] = ti->bytes;
    g_cache_type[g_cache_n]  = ti->type;
    g_cache_off[g_cache_n]   = ti->offset;
    g_cache_n++;
    return d;
}

static int metal_matmul_inner(TensorInfo *ti,
                              const float *X, float *Y,
                              u64 batch, u64 rows, u64 cols, bool trans) {
    if (metal_ensure_ready() != 0) return -1;
    if (ti->type >= 31 || metal_type_suffix[ti->type] == NULL) return -1;

    id<MTLBuffer> d_w = metal_cache_get(ti);
    if (!d_w) return -1;

    id<MTLBuffer> d_x = [g_device newBufferWithBytes:X length:(NSUInteger)(batch * cols * sizeof(float)) options:MTLResourceStorageModeShared];
    id<MTLBuffer> d_y = [g_device newBufferWithLength:(NSUInteger)(batch * rows * sizeof(float)) options:MTLResourceStorageModeShared];
    if (!d_x || !d_y) return -1;

    struct MetalMatmulParams mp = { rows, cols, batch };
    id<MTLBuffer> d_p = [g_device newBufferWithBytes:&mp length:sizeof(mp) options:MTLResourceStorageModeShared];

    id<MTLComputePipelineState> pipe = metal_matmul_pipeline(ti->type, trans);
    MTLSize tptg = MTLSizeMake(METAL_THREADS, 1, 1);
    MTLSize grid = trans ? MTLSizeMake((rows + 255) / 256, batch, 1)
                         : MTLSizeMake((rows + 7) / 8, batch, 1);
    metal_execute(pipe, grid, tptg, d_w, d_x, d_y, g_tables, d_p);

    memcpy(Y, d_y.contents, (size_t)(batch * rows * sizeof(float)));
    return 0;
}

int metal_matvec(TensorInfo *ti, const float *x, float *y,
                 u64 rows, u64 cols, bool trans) {
    if (!ti || !ti->data || !x || !y || rows == 0 || cols == 0) return -1;
    if (rows * cols > ti->n_element) return -1; /* dim sanity (CPU checks dims) */

    pthread_mutex_lock(&g_lock);
    @autoreleasepool {
        int rc = metal_matmul_inner(ti, x, y, 1, rows, cols, trans);
        pthread_mutex_unlock(&g_lock);
        return rc;
    }
}

int metal_matmat(TensorInfo *ti, const float *X, float *Y,
                 u64 batch, u64 rows, u64 cols, bool trans) {
    if (!ti || !ti->data || !X || !Y || batch == 0 || rows == 0 || cols == 0) return -1;
    if (rows * cols > ti->n_element) return -1;

    pthread_mutex_lock(&g_lock);
    @autoreleasepool {
        int rc = metal_matmul_inner(ti, X, Y, batch, rows, cols, trans);
        pthread_mutex_unlock(&g_lock);
        return rc;
    }
}

void metal_shutdown(void) {
    pthread_mutex_lock(&g_lock);
    for (int i = 0; i < g_cache_n; i++) g_cache_dev[i] = nil;
    g_cache_n = 0;
    g_pipe_dequant = nil;
    g_pipe_dot = nil;
    for (int t = 0; t < 31; t++)
        for (int o = 0; o < 2; o++) g_pipes[t][o] = nil;
    g_tables = nil;
    g_library = nil;
    g_queue = nil;
    g_device = nil;
    pthread_mutex_unlock(&g_lock);
}
