/*
 * metal.metal — Metal batch dequantization kernels.
 *
 * Line-for-line port of the device side of backend/gpu/gpu.cu, which is
 * itself bit-exact against the scalar reference in quants.c: each
 * thread dequantizes one element directly from the raw GGUF bytes that
 * were uploaded to device memory, using identical integer math (the
 * manual f16/bf16 bit manipulation, not MSL `half` conversions), so
 * GPU output is bit-for-bit comparable to gguf_dequant().
 *
 * The IQ importance grids / value tables live on the host in
 * quants.c; the host copies them into one device buffer (layout below)
 * at first use, replacing the __constant__ memory of the CUDA version.
 *
 * This file is embedded into the host binary as a string
 * (metal_msl.h, generated by the Makefile) and compiled with
 * newLibraryWithSource() at first use.
 */

#include <metal_stdlib>
using namespace metal;

/* ================================================================
 * GGUF quant type codes — keep in sync with GGUFType in def.h
 * ================================================================ */

#define GGUF_TYPE_F32     0
#define GGUF_TYPE_F16     1
#define GGUF_TYPE_Q4_0    2
#define GGUF_TYPE_Q4_1    3
#define GGUF_TYPE_Q5_0    6
#define GGUF_TYPE_Q5_1    7
#define GGUF_TYPE_Q8_0    8
#define GGUF_TYPE_Q8_1    9
#define GGUF_TYPE_Q2_K    10
#define GGUF_TYPE_Q3_K    11
#define GGUF_TYPE_Q4_K    12
#define GGUF_TYPE_Q5_K    13
#define GGUF_TYPE_Q6_K    14
#define GGUF_TYPE_Q8_K    15
#define GGUF_TYPE_IQ2_XXS 16
#define GGUF_TYPE_IQ2_XS  17
#define GGUF_TYPE_IQ3_XXS 18
#define GGUF_TYPE_IQ1_S   19
#define GGUF_TYPE_IQ4_NL  20
#define GGUF_TYPE_IQ3_S   21
#define GGUF_TYPE_IQ2_S   22
#define GGUF_TYPE_IQ4_XS  23
#define GGUF_TYPE_I8      24
#define GGUF_TYPE_I16     25
#define GGUF_TYPE_I32     26
#define GGUF_TYPE_I64     27
#define GGUF_TYPE_F64     28
#define GGUF_TYPE_IQ1_M   29
#define GGUF_TYPE_BF16    30

/* ================================================================
 * Combined table buffer (float element offsets) — must match
 * metal_tables_init() in metal.m: iq2_xxs (256), iq2_xs (512),
 * iq3_xxs (256), iq1_s (256), iq4_nl (256), iq3_s (512) floats.
 * ================================================================ */

#define IQ2_XXS_TAB 0
#define IQ2_XS_TAB  256
#define IQ3_XXS_TAB 768
#define IQ1_S_TAB   1024
#define IQ4_NL_TAB  1280
#define IQ3_S_TAB   1536

/* ================================================================
 * Params structs — layout must match the host definitions in
 * metal.m (same field order and widths).
 * ================================================================ */

/* NOTE: MSL forbids 64-bit integer fields in a buffer pointee type, so
 * every 64-bit value is carried as a `uint2` (x = low word, y = high
 * word).  The host structs in metal.m use the matching u64 layout, which
 * is identical on a little-endian ABI. */
struct DequantParams {
    uint32_t type;
    uint32_t _pad;
    uint2 start_i;   /* block-aligned start (buffer begins here) */
    uint2 i0;        /* first requested element                   */
    uint2 nb;        /* element count                             */
};

struct MatmulParams {
    uint2 rows;
    uint2 cols;
    uint2 batch;
};

static inline uint64_t u2_to_u64(uint2 v) {
    return ((uint64_t)v.y << 32) | (uint64_t)v.x;
}

/* ================================================================
 * Device helpers
 * ================================================================ */

/* Identical math to f16_to_f32() in quants.c / gpu.cu. */
static inline float f16_to_f32(uint16_t bits) {
    uint32_t sign = (uint32_t)(bits >> 15) << 31;
    uint32_t exp  = (bits >> 10) & 0x1f;
    uint32_t mant = bits & 0x3ff;
    uint32_t f32;
    if (exp == 0) {
        if (mant == 0) {
            f32 = sign;
        } else {
            int e = 1 - 15;
            while ((mant & 0x400) == 0) { mant <<= 1; e--; }
            mant &= 0x3ff;
            f32 = sign | ((uint32_t)(e + 127) << 23) | (mant << 13);
        }
    } else if (exp == 31) {
        f32 = sign | (0xffu << 23) | (mant << 13); /* inf / nan */
    } else {
        f32 = sign | ((uint32_t)(exp - 15 + 127) << 23) | (mant << 13);
    }
    union { uint32_t u; float f; } v = { f32 };
    return v.f;
}

static inline float bf16_to_f32(uint16_t bits) {
    union { uint32_t u; float f; } v = { (uint32_t)bits << 16 };
    return v.f;
}

/* Alignment-safe multi-byte loads.  GGUF quant blocks start on odd byte
 * strides (e.g. q5_0 is 22 bytes), so a raw *(const uint32_t*) cast
 * could fault; assembling from bytes is correct for every alignment. */
static inline uint16_t ld_u16(device const uint8_t *p) {
    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);
}
static inline uint32_t ld_u32(device const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t ld_u64(device const uint8_t *p) {
    return (uint64_t)ld_u32(p) | ((uint64_t)ld_u32(p + 4) << 32);
}
static inline float ld_f32(device const uint8_t *p) {
    union { uint32_t u; float f; } v = { ld_u32(p) };
    return v.f;
}
/* Metal has no `double`, so f64 is converted to f32 with round-to-nearest
 * -even integer math (matching a C `(float)double` cast). */
static inline float u32_as_f32(uint32_t u) {
    union { uint32_t u; float f; } v = { u };
    return v.f;
}
static inline float f64_to_f32(uint64_t bits) {
    uint32_t sign = (uint32_t)(bits >> 63) << 31;
    uint32_t exp  = (uint32_t)((bits >> 52) & 0x7FF);
    uint64_t mant = bits & 0xFFFFFFFFFFFFFULL;

    if (exp == 0x7FF) {
        if (mant == 0) return u32_as_f32(sign | 0x7F800000u); /* inf */
        uint32_t payload = (uint32_t)(mant >> 29);
        return u32_as_f32(sign | 0x7F800000u | payload | 0x400000u); /* nan */
    }
    if (exp == 0) return u32_as_f32(sign); /* double subnormal -> f32 0 */
    int32_t e = (int32_t)exp - 1023;
    if (e >= 128) return u32_as_f32(sign | 0x7F800000u); /* overflow -> inf */
    if (e >= -126) {
        uint32_t fexp = (uint32_t)(e + 127);
        uint32_t m_hi = (uint32_t)(mant >> 29);
        uint32_t rem  = (uint32_t)(mant & 0x1FFFFFFFULL);
        if (rem > 0x10000000u || (rem == 0x10000000u && (m_hi & 1u))) {
            if (++m_hi == 0x800000u) {
                m_hi = 0;
                if (++fexp >= 0xFFu) return u32_as_f32(sign | 0x7F800000u);
            }
        }
        return u32_as_f32(sign | (fexp << 23) | (m_hi & 0x7FFFFFu));
    }
    /* e < -126: subnormal f32 or zero. */
    int32_t rshift = -e - 97;
    if (rshift >= 64) return u32_as_f32(sign);
    uint64_t sig = (1ULL << 52) | mant;
    uint32_t q = (uint32_t)(sig >> rshift);
    uint64_t rem = sig & ((1ULL << rshift) - 1ULL);
    uint64_t halfway = 1ULL << (rshift - 1);
    if (rem > halfway || (rem == halfway && (q & 1u))) q++;
    if (q >= 0x800000u) return u32_as_f32(sign | 0x00800000u);
    return u32_as_f32(sign | q);
}

static inline void q4k_scale_min(device const uint8_t *s, uint32_t sb, thread uint8_t *scale, thread uint8_t *min) {
    uint8_t d  = s[sb & 3];
    uint8_t m  = s[4 + (sb & 3)];
    uint8_t md = s[8 + (sb & 3)];
    if (sb < 4) {
        *scale = d & 0x3F;
        *min   = m & 0x3F;
    } else {
        *scale = (md & 0x0F) | ((d >> 2) & 0x30);
        *min   = (md >> 4) | ((m >> 2) & 0x30);
    }
}

/* ================================================================
 * Simple (non-block) types
 * ================================================================ */

static inline float dequant_F32(device const uint8_t *data, uint64_t i, device const float *tables) {
    return ld_f32(data + i * 4);
}
static inline float dequant_F16(device const uint8_t *data, uint64_t i, device const float *tables) {
    return f16_to_f32(ld_u16(data + i * 2));
}
static inline float dequant_BF16(device const uint8_t *data, uint64_t i, device const float *tables) {
    return bf16_to_f32(ld_u16(data + i * 2));
}
static inline float dequant_F64(device const uint8_t *data, uint64_t i, device const float *tables) {
    return f64_to_f32(ld_u64(data + i * 8));
}
static inline float dequant_I8(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int8_t)data[i];
}
static inline float dequant_I16(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int16_t)ld_u16(data + i * 2);
}
static inline float dequant_I32(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int32_t)ld_u32(data + i * 4);
}
static inline float dequant_I64(device const uint8_t *data, uint64_t i, device const float *tables) {
    return (float)(int64_t)ld_u64(data + i * 8);
}

/* ================================================================
 * Simple block types (block_size = 32)
 * ================================================================ */

static inline float dequant_Q8_0(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 34;
    float d = f16_to_f32(ld_u16(blk));
    return (float)(int8_t)blk[2 + o] * d;
}

static inline float dequant_Q8_1(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 40;
    float d = ld_f32(blk);
    return (float)(int8_t)blk[8 + o] * d;
}

static inline float dequant_Q4_0(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 18;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t nib = (blk[2 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return ((float)(int32_t)nib - 8.0f) * d;
}

static inline float dequant_Q4_1(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 20;
    float d = f16_to_f32(ld_u16(blk));
    float m = f16_to_f32(ld_u16(blk + 2));
    uint32_t nib = (blk[4 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return (float)nib * d + m;
}

static inline float dequant_Q5_0(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 22;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t qh = ld_u32(blk + 2);
    uint32_t hi = (qh >> o) & 1;
    uint32_t lo = (blk[6 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return ((float)(int32_t)((hi << 4) | lo) - 16.0f) * d;
}

static inline float dequant_Q5_1(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 5; uint32_t o = i & 31;
    device const uint8_t *blk = data + bi * 24;
    float d = f16_to_f32(ld_u16(blk));
    float m = f16_to_f32(ld_u16(blk + 2));
    uint32_t qh = ld_u32(blk + 4);
    uint32_t hi = (qh >> o) & 1;
    uint32_t lo = (blk[8 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return (float)((hi << 4) | lo) * d + m;
}

/* ================================================================
 * K-quant types (block_size = 256)
 * ================================================================ */

static inline float dequant_Q8_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 292;
    float d = ld_f32(blk);
    float bs = f16_to_f32(ld_u16(blk + 4 + 2 * (o >> 4)));
    return (float)(int8_t)blk[36 + o] * bs * d;
}

static inline float dequant_Q6_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 210;
    float d = f16_to_f32(ld_u16(blk + 208));
    int32_t sc = (int8_t)blk[192 + (o >> 4)];

    uint32_t hl      = o & 127;          /* position within 128-element half   */
    uint32_t which   = hl >> 5;          /* 0..3: which 32-element sub-group   */
    uint32_t l       = hl & 31;          /* 0..31: position inside sub-group   */
    uint32_t half_idx = o >> 7;          /* 0 or 1: which 128-element half     */

    uint32_t ql_off  = (half_idx << 6) + ((which & 1) << 5) + l;
    uint32_t lo      = (which >= 2) ? ((blk[ql_off] >> 4) & 0xF)
                                    :  (blk[ql_off] & 0xF);

    uint32_t qh_off  = 128 + (half_idx << 5) + l;
    uint32_t hi      = (blk[qh_off] >> (which * 2)) & 0x3;

    int32_t q  = (int32_t)(lo | (hi << 4)) - 32;
    return d * (float)sc * (float)q;
}

static inline float dequant_Q5_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 176;
    float d    = f16_to_f32(ld_u16(blk));
    float dmin = f16_to_f32(ld_u16(blk + 2));
    uint32_t sb = o >> 5;
    uint8_t sc, mn;
    q4k_scale_min(blk + 4, sb, &sc, &mn);
    uint32_t g  = o >> 6;
    uint32_t nb = (o >> 5) & 1;
    uint32_t bc = o & 31;
    uint32_t lo = (blk[48 + g * 32 + bc] >> (nb * 4)) & 0xF;
    uint32_t hi = (blk[16 + (o & 31)] >> (o >> 5)) & 1;
    int32_t q  = (int32_t)(lo | (hi << 4));
    return d * (float)sc * (float)q - dmin * (float)mn;
}

static inline float dequant_Q4_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 144;
    float d    = f16_to_f32(ld_u16(blk));
    float dmin = f16_to_f32(ld_u16(blk + 2));
    uint32_t sb = o >> 5;
    uint8_t sc, mn;
    q4k_scale_min(blk + 4, sb, &sc, &mn);
    uint32_t g  = o >> 6;
    uint32_t nb = (o >> 5) & 1;
    uint32_t bc = o & 31;
    uint32_t nib = (blk[16 + g * 32 + bc] >> (nb * 4)) & 0xF;
    return d * (float)sc * (float)nib - dmin * (float)mn;
}

static inline float dequant_Q3_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 110;
    float d = f16_to_f32(ld_u16(blk + 108));
    uint32_t s = o >> 4;
    uint32_t g  = o >> 7;
    uint32_t pr = (o >> 5) & 3;
    uint32_t bc = o & 31;
    uint32_t lo = (blk[32 + g * 32 + bc] >> (pr * 2)) & 3;
    uint32_t hi = (blk[o & 31] >> (o >> 5)) & 1;
    uint32_t sc_low  = (blk[96 + (s & 7)]  >> (s >= 8 ? 4 : 0)) & 0xF;
    uint32_t sc_high = (blk[104 + (s & 3)] >> ((s >> 2) * 2)) & 0x3;
    int32_t sc = (int32_t)(sc_low | (sc_high << 4)) - 32;
    int32_t q  = (int32_t)(lo | (hi << 2)) - 4;
    return d * (float)sc * (float)q;
}

static inline float dequant_Q2_K(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 84;
    float d  = f16_to_f32(ld_u16(blk + 64 + 16));
    float mn = f16_to_f32(ld_u16(blk + 64 + 16 + 2));
    uint32_t sb  = o >> 4;
    uint32_t sc  = blk[64 + (sb >> 1)];
    if (sb & 1) sc >>= 4; else sc &= 0xF;
    uint32_t q2 = (blk[(o >> 2)] >> ((o & 3) << 1)) & 0x3;
    int32_t q  = (int32_t)q2 - (int32_t)((blk[(o >> 3)] >> (o & 7)) & 1) * 4;
    float sc_f = (float)(int32_t)sc;
    return d * sc_f * (float)q - mn;
}

/* ================================================================
 * IQ (importance-matrix-aware) types
 * ================================================================ */

static inline float dequant_IQ2_XXS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 66;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t q = (blk[2 + (o >> 2)] >> ((o & 3) << 1)) & 0x3;
    uint32_t sign_bit = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    float v = tables[IQ2_XXS_TAB + (q | (sign_bit << 2))];
    return v * d;
}

static inline float dequant_IQ2_XS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 74;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t sh = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t q  = (blk[2 + 32 + (o >> 2)] >> ((o & 3) << 1)) & 0x3;
    uint32_t idx = q | (sh << 2);
    int8_t  sc = (int8_t)(blk[2 + 32 + 64 + (o >> 4)]);
    return d * (float)sc * tables[IQ2_XS_TAB + idx];
}

static inline float dequant_IQ3_XXS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 98;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t qh = (blk[2 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t qm = (blk[2 + 8 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t ql = (blk[2 + 8 + 32 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t grp = (blk[2 + 8 + 32 + 128 + (o >> 3)] >> ((o & 7) << 1)) & 0x3;
    uint32_t idx = ql | (qm << 4) | (qh << 5) | (grp << 6);
    int8_t  sc  = (int8_t)(blk[2 + 8 + 32 + 128 + 64 + (o >> 4)]);
    return d * (float)sc * tables[IQ3_XXS_TAB + idx];
}

static inline float dequant_IQ1_S(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 110;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t q  = ((blk[2 + (o >> 3)] >> (o & 7)) & 1) |
                  (((blk[2 + 32 + (o >> 3)] >> (o & 7)) & 1) << 1);
    uint32_t idx = q | (((o >> 4) & 0xF) << 2);
    return d * tables[IQ1_S_TAB + idx];
}

static inline float dequant_IQ4_NL(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 50;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t q = (blk[2 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    return d * tables[IQ4_NL_TAB + (q | ((o & 0xF) << 4))];
}

static inline float dequant_IQ1_M(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 56;
    float d = f16_to_f32(ld_u16(blk + 54));
    uint32_t sb    = o >> 4;
    uint32_t sc    = (blk[sb >> 1] >> ((sb & 1) << 2)) & 0xF;
    float sc_f = (float)(int32_t)sc + 1.0f;
    uint32_t val  = (blk[8 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t sign = (blk[8 + 32 + (o >> 3)] >> (o & 7)) & 1;
    float v = sign ? -(float)val : (float)val;
    return v * sc_f * d;
}

static inline float dequant_IQ3_S(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 110;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t sign = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t qh   = (blk[2 + 32 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t qm   = (blk[2 + 32 + 8 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t ql   = (blk[2 + 32 + 8 + 32 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t idx  = ql | (qm << 4) | (qh << 5) | (sign << 6);
    int8_t  sc   = (int8_t)blk[2 + 32 + 8 + 32 + 128 + (o >> 4)];
    return d * (float)sc * tables[IQ3_S_TAB + idx];
}

static inline float dequant_IQ2_S(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 82;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t sign = (blk[2 + (o >> 3)] >> (o & 7)) & 1;
    uint32_t qh   = (blk[2 + 32 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t ql   = (blk[2 + 32 + 8 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t idx  = ql | (qh << 4) | (sign << 5);
    int8_t  sc   = (int8_t)blk[2 + 32 + 8 + 128 + (o >> 4) + ((o >> 4) & 1) * 16];
    uint32_t sc_l = (blk[2 + 32 + 8 + 128 + (o >> 5)] >> ((o & 31) >> 2)) & 0x3;
    float sc_f = (float)sc + 0.125f * (float)(int32_t)sc_l;
    return d * sc_f * tables[IQ2_XS_TAB + idx];
}

static inline float dequant_IQ4_XS(device const uint8_t *data, uint64_t i, device const float *tables) {
    uint64_t bi = i >> 8; uint32_t o = i & 255;
    device const uint8_t *blk = data + bi * 136;
    float d = f16_to_f32(ld_u16(blk));
    uint32_t qh = (blk[2 + (o >> 5)] >> (o & 31)) & 1;
    uint32_t ql = (blk[2 + 8 + (o >> 1)] >> ((o & 1) << 2)) & 0xF;
    uint32_t q  = ql | (qh << 4);
    int8_t  sc_l = (int8_t)blk[2 + 8 + 128 + (o >> 4)];
    int8_t  sc_h = (int8_t)blk[2 + 8 + 128 + 16 + (o >> 4)];
    float sc = (float)(int32_t)sc_l + ((float)(int32_t)sc_h / 127.0f);
    return d * sc * tables[IQ4_NL_TAB + q];
}

/* ================================================================
 * Runtime-switch dispatcher (dequant / dot kernels only; the matmul
 * kernels below are compile-time specialized per type).
 * ================================================================ */

static inline float dequant_one(uint32_t type, device const uint8_t *data, uint64_t i, device const float *tables) {
    switch (type) {
        case GGUF_TYPE_F32:     return dequant_F32(data, i, tables);
        case GGUF_TYPE_F16:     return dequant_F16(data, i, tables);
        case GGUF_TYPE_BF16:    return dequant_BF16(data, i, tables);
        case GGUF_TYPE_F64:     return dequant_F64(data, i, tables);
        case GGUF_TYPE_I8:      return dequant_I8(data, i, tables);
        case GGUF_TYPE_I16:     return dequant_I16(data, i, tables);
        case GGUF_TYPE_I32:     return dequant_I32(data, i, tables);
        case GGUF_TYPE_I64:     return dequant_I64(data, i, tables);
        case GGUF_TYPE_Q8_0:    return dequant_Q8_0(data, i, tables);
        case GGUF_TYPE_Q8_1:    return dequant_Q8_1(data, i, tables);
        case GGUF_TYPE_Q4_0:    return dequant_Q4_0(data, i, tables);
        case GGUF_TYPE_Q4_1:    return dequant_Q4_1(data, i, tables);
        case GGUF_TYPE_Q5_0:    return dequant_Q5_0(data, i, tables);
        case GGUF_TYPE_Q5_1:    return dequant_Q5_1(data, i, tables);
        case GGUF_TYPE_Q8_K:    return dequant_Q8_K(data, i, tables);
        case GGUF_TYPE_Q6_K:    return dequant_Q6_K(data, i, tables);
        case GGUF_TYPE_Q5_K:    return dequant_Q5_K(data, i, tables);
        case GGUF_TYPE_Q4_K:    return dequant_Q4_K(data, i, tables);
        case GGUF_TYPE_Q3_K:    return dequant_Q3_K(data, i, tables);
        case GGUF_TYPE_Q2_K:    return dequant_Q2_K(data, i, tables);
        case GGUF_TYPE_IQ2_XXS: return dequant_IQ2_XXS(data, i, tables);
        case GGUF_TYPE_IQ2_XS:  return dequant_IQ2_XS(data, i, tables);
        case GGUF_TYPE_IQ3_XXS: return dequant_IQ3_XXS(data, i, tables);
        case GGUF_TYPE_IQ1_S:   return dequant_IQ1_S(data, i, tables);
        case GGUF_TYPE_IQ4_NL:  return dequant_IQ4_NL(data, i, tables);
        case GGUF_TYPE_IQ1_M:   return dequant_IQ1_M(data, i, tables);
        case GGUF_TYPE_IQ3_S:   return dequant_IQ3_S(data, i, tables);
        case GGUF_TYPE_IQ2_S:   return dequant_IQ2_S(data, i, tables);
        case GGUF_TYPE_IQ4_XS:  return dequant_IQ4_XS(data, i, tables);
        default:                return 0.0f;
    }
}

/* ================================================================
 * Kernels
 * ================================================================ */

/* Dequantize elements [i0, i0+nb) into out.  data points at the start
 * of the block containing element start_i (start_i is block-aligned),
 * so a thread dequantizes relative element (i0 + j) - start_i. */
kernel void dequant_range(device const uint8_t *data [[buffer(0)]],
                          device float *out [[buffer(1)]],
                          device const float *tables [[buffer(2)]],
                          constant struct DequantParams &p [[buffer(3)]],
                          uint tid [[thread_position_in_grid]],
                          uint tptg [[threads_per_threadgroup]],
                          uint ntg  [[threadgroups_per_grid]]) {
    uint64_t start_i = u2_to_u64(p.start_i);
    uint64_t i0      = u2_to_u64(p.i0);
    uint64_t nb      = u2_to_u64(p.nb);
    uint64_t idx    = (uint64_t)tid;
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t j = idx; j < nb; j += stride) {
        out[j] = dequant_one(p.type, data, (i0 + j) - start_i, tables);
    }
}

/* Fused dequant + dot: sum_{j=0}^{n-1} w[i0+j] * x[j], one partial sum
 * per threadgroup, host-side final reduction. */
kernel void dequant_dot(device const uint8_t *data [[buffer(0)]],
                        device const float *x [[buffer(1)]],
                        device float *partial [[buffer(2)]],
                        device const float *tables [[buffer(3)]],
                        constant struct DequantParams &p [[buffer(4)]],
                        uint tid [[thread_position_in_threadgroup]],
                        uint tptg [[threads_per_threadgroup]],
                        uint idx [[thread_position_in_grid]],
                        uint tg  [[threadgroup_position_in_grid]],
                        uint ntg [[threadgroups_per_grid]]) {
    threadgroup float sh[256];
    uint64_t start_i = u2_to_u64(p.start_i);
    uint64_t i0      = u2_to_u64(p.i0);
    uint64_t nb      = u2_to_u64(p.nb);
    uint64_t stride = (uint64_t)ntg * tptg;
    float sum = 0.0f;
    for (uint64_t j = idx; j < nb; j += stride) {
        sum += dequant_one(p.type, data, (i0 + j) - start_i, tables) * x[j];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint s = tptg >> 1; s > 0; s >>= 1) {
        if (tid < s) sh[tid] += sh[tid + s];
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (tid == 0) partial[tg] = sh[0];
}

/* ================================================================
 * Persistent-weight matmul kernels
 *
 * w points at the device copy of the whole tensor; all indices are
 * FLAT element indices (i = r*cols + c / c*rows + r), identical to
 * the scalar reference gguf_dequant().  GGUF quantized tensors have
 * no per-row padding — block boundaries may fall mid-row — so the
 * dequant helpers must derive the block from the flat index, never
 * from a precomputed row pointer.
 *
 * Each type is instantiated as its own kernel via the X-macro below
 * (the MSL analogue of the CUDA template instantiations), so the
 * per-element decode is straight-line code in the inner loop.
 * ================================================================ */

#define METAL_TYPE_LIST(X) \
    X(F32) X(F16) X(Q4_0) X(Q4_1) \
    X(Q5_0) X(Q5_1) X(Q8_0) X(Q8_1) \
    X(Q2_K) X(Q3_K) X(Q4_K) X(Q5_K) \
    X(Q6_K) X(Q8_K) X(IQ2_XXS) X(IQ2_XS) \
    X(IQ3_XXS) X(IQ1_S) X(IQ4_NL) X(IQ3_S) \
    X(IQ2_S) X(IQ4_XS) X(I8) X(I16) \
    X(I32) X(I64) X(F64) X(IQ1_M) \
    X(BF16)

/* Non-transposed: y[b*rows + r] = sum_c w[r*cols + c] * x[b*cols + c].
 * One SIMD group (warp) per output row; lanes stride c by 32 so each
 * iteration covers exactly one quant block (QK=32 types) — coalesced
 * loads.  The per-row sum is reduced through threadgroup memory (an
 * extra all-threads barrier keeps early-exit rows from deadlocking).
 * Grid is 1-D: [(ceil(rows/8)) * batch]; the batch index is derived
 * from the tile count. */
#define DEFINE_MATMUL_NT(T)                                                            \
kernel void matmul_nt_##T(device const uint8_t *w [[buffer(0)]],                       \
                          device const float *x [[buffer(1)]],                         \
                          device float *y [[buffer(2)]],                               \
                          device const float *tables [[buffer(3)]],                    \
                          constant struct MatmulParams &p [[buffer(4)]],               \
                          uint tid [[thread_position_in_threadgroup]],                 \
                          uint tg [[threadgroup_position_in_grid]]) {                  \
    threadgroup float sh[256];                                                         \
    uint64_t rows  = u2_to_u64(p.rows);                                                \
    uint64_t cols  = u2_to_u64(p.cols);                                                \
    uint64_t tiles = (rows + 7) / 8;                                                   \
    uint64_t b     = (uint64_t)tg / tiles;                                             \
    uint64_t tile  = (uint64_t)tg % tiles;                                             \
    uint simd = tid >> 5;                                                              \
    uint lane = tid & 31;                                                              \
    uint64_t r = tile * 8 + simd;                                                      \
    float sum = 0.0f;                                                                  \
    if (r < rows) {                                                                    \
        device const float *xr = x + b * cols;                                         \
        for (uint64_t c = lane; c < cols; c += 32)                                     \
            sum += dequant_##T(w, r * cols + c, tables) * xr[c];                       \
    }                                                                                  \
    sh[tid] = sum;                                                                     \
    threadgroup_barrier(mem_flags::mem_threadgroup);                                   \
    if (lane == 0 && r < rows) {                                                       \
        float s = 0.0f;                                                                \
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];                          \
        y[b * rows + r] = s;                                                           \
    }                                                                                  \
}
METAL_TYPE_LIST(DEFINE_MATMUL_NT)
#undef DEFINE_MATMUL_NT

/* Transposed: y[b*rows + idx] = sum_c w[c*rows + idx] * x[b*cols + c].
 * One thread per output element; 256 threads cover 256 outputs, so
 * per c the 32 lanes of a SIMD group read the same quant block (QK=32
 * types: block headers broadcast, elements gathered within the
 * block).  Grid is 1-D: [(ceil(rows/256)) * batch]. */
#define DEFINE_MATMUL_T(T)                                                             \
kernel void matmul_t_##T(device const uint8_t *w [[buffer(0)]],                        \
                         device const float *x [[buffer(1)]],                          \
                         device float *y [[buffer(2)]],                                \
                         device const float *tables [[buffer(3)]],                     \
                         constant struct MatmulParams &p [[buffer(4)]],                \
                         uint tid [[thread_position_in_threadgroup]],                  \
                         uint tptg [[threads_per_threadgroup]],                        \
                         uint tg [[threadgroup_position_in_grid]]) {                   \
    uint64_t rows  = u2_to_u64(p.rows);                                                \
    uint64_t cols  = u2_to_u64(p.cols);                                                \
    uint64_t tiles = (rows + tptg - 1) / tptg;                                         \
    uint64_t b     = (uint64_t)tg / tiles;                                             \
    uint64_t idx   = ((uint64_t)tg % tiles) * tptg + tid;                              \
    if (idx >= rows) return;                                                           \
    device const float *xr = x + b * cols;                                             \
    float sum = 0.0f;                                                                  \
    for (uint64_t c = 0; c < cols; c++)                                                \
        sum += dequant_##T(w, c * rows + idx, tables) * xr[c];                         \
    y[b * rows + idx] = sum;                                                           \
}
METAL_TYPE_LIST(DEFINE_MATMUL_T)
#undef DEFINE_MATMUL_T

/* ================================================================
 * Block-level vectorized Q4_K dot product (non-transposed)
 *
 * The generic kernels above decode one element per iteration, so a
 * 256-element block's header (d, dmin) and its 6-bit scale/min pair are
 * recomputed for every element — about 8x redundant work on K-quants,
 * which is where decode-bound models spend their time.
 *
 * Here one SIMD group still owns one output row, but for every fully
 * contained block each lane owns 8 CONSECUTIVE elements:
 *   - d / dmin and one scale/min pair are decoded once for those 8
 *     elements (o0 = lane*8 keeps them inside a single 32-group, so a
 *     single q4k_scale_min() suffices);
 *   - the 8 nibbles live in 8 contiguous bytes -> two ld_u32;
 *   - x is read as two float4.
 * value = d*sc*q - dmin*mn is affine in q, so the 8-element dot folds
 * into s*sum(q*x) - m*sum(x) with two FMAs instead of 8 decodes.
 *
 * Blocks only partially covered by the row (its head and tail) keep the
 * scalar decoder, so the kernel is exact for any row length/offset.
 * The host only selects it when x is 16-byte aligned and the row length
 * is a multiple of 4 (float4 loads).
 * ================================================================ */
kernel void matmul_nt_Q4K_F(device const uint8_t *w [[buffer(0)]],
                            device const float *x [[buffer(1)]],
                            device float *y [[buffer(2)]],
                            device const float *tables [[buffer(3)]],
                            constant struct MatmulParams &p [[buffer(4)]],
                            uint tid [[thread_position_in_threadgroup]],
                            uint tg [[threadgroup_position_in_grid]]) {
    threadgroup float sh[256];
    uint64_t rows  = u2_to_u64(p.rows);
    uint64_t cols  = u2_to_u64(p.cols);
    uint64_t tiles = (rows + 7) / 8;
    uint64_t b     = (uint64_t)tg / tiles;
    uint64_t tile  = (uint64_t)tg % tiles;
    uint simd = tid >> 5;
    uint lane = tid & 31;
    uint64_t r = tile * 8 + simd;
    float sum = 0.0f;
    if (r < rows) {
        device const float *xr = x + b * cols;
        uint64_t i0   = r * cols;          /* first element of the row  */
        uint64_t i1   = i0 + cols;         /* one past the last         */
        uint64_t bs   = (i0 + 255) >> 8;   /* first fully covered block */
        uint64_t be   = i1 >> 8;           /* one past the last one     */
        uint64_t hend = (bs * 256 < i1) ? bs * 256 : i1;

        /* Head: [i0, hend) — scalar decoder. */
        for (uint64_t c = lane; c < hend - i0; c += 32)
            sum += dequant_Q4_K(w, i0 + c, tables) * xr[c];

        /* Fully covered blocks — vectorized. */
        for (uint64_t bi = bs; bi < be; bi++) {
            device const uint8_t *blk = w + bi * 144;
            float d    = f16_to_f32(ld_u16(blk));
            float dmin = f16_to_f32(ld_u16(blk + 2));
            uint32_t o0 = lane * 8;
            uint8_t sc, mn;
            q4k_scale_min(blk + 4, o0 >> 5, &sc, &mn);
            float s = d * (float)sc;
            float m = dmin * (float)mn;

            /* 8 nibbles in 8 contiguous bytes of qs.  With o0 = lane*8:
             * g = o0>>6 = lane>>3 and bc = o0&31 = (lane&3)*8, and both
             * stay constant over the 8 elements (8 divides 32 and 64). */
            uint32_t qoff = 16 + (lane >> 3) * 32 + ((lane & 3) * 8);
            uint32_t w0   = ld_u32(blk + qoff);
            uint32_t w1   = ld_u32(blk + qoff + 4);
            uint32_t hi   = (o0 >> 5) & 1;              /* low/high nibble */
            uint32_t msk  = hi ? 0xF0F0F0F0u : 0x0F0F0F0Fu;
            uint32_t a0   = (w0 & msk) >> (hi ? 4 : 0);
            uint32_t a1   = (w1 & msk) >> (hi ? 4 : 0);

            uint64_t xc = (bi * 256 - i0) + (uint64_t)lane * 8;
            device const float4 *xv = (device const float4 *)(xr + xc);
            float4 v0 = xv[0];
            float4 v1 = xv[1];

            float sq = (float)(a0 & 0xFF)        * v0.x +
                       (float)((a0 >> 8) & 0xFF)  * v0.y +
                       (float)((a0 >> 16) & 0xFF) * v0.z +
                       (float)((a0 >> 24) & 0xFF) * v0.w +
                       (float)(a1 & 0xFF)        * v1.x +
                       (float)((a1 >> 8) & 0xFF)  * v1.y +
                       (float)((a1 >> 16) & 0xFF) * v1.z +
                       (float)((a1 >> 24) & 0xFF) * v1.w;
            float sx = (v0.x + v0.y) + (v0.z + v0.w) +
                       (v1.x + v1.y) + (v1.z + v1.w);
            sum += s * sq - m * sx;
        }

        /* Tail: [max(be*256, i0), i1) — scalar decoder. */
        uint64_t tstart = (be * 256 > i0) ? be * 256 : i0;
        if (tstart < hend) tstart = hend;
        for (uint64_t c = (tstart - i0) + lane; c < cols; c += 32)
            sum += dequant_Q4_K(w, i0 + c, tables) * xr[c];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (lane == 0 && r < rows) {
        float s = 0.0f;
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];
        y[b * rows + r] = s;
    }
}

/* ================================================================
 * Block-level vectorized K-quant dot products (non-transposed)
 *
 * Same shape as matmul_nt_Q4K_F above: one SIMD group per output row,
 * per 256-element block each lane owns 8 CONSECUTIVE elements, so the
 * per-block header and the per-sub-block scale are decoded once for
 * those 8 elements instead of 8 times.  For every K-quant the value is
 * affine in the raw code q (value = a*q + b with a, b constant across
 * the 8 elements), so the 8-element dot folds into
 *      a * sum(q*x) + b * sum(x)
 * with two FMAs.  Row head/tail blocks keep the scalar decoder, so the
 * result is exact for any row length and offset.
 *
 * Host selects these only when x is 16-byte aligned and the row length
 * is a multiple of 4 (float4 loads) and at least one full block fits.
 * ================================================================ */

/* Q5_K (176 = 2 d + 2 dmin + 12 scales + 32 qh + 128 qs).
 * Identical to Q4_K plus a 1-bit high plane: qh byte (o&31), bit (o>>5).
 * For o0 = lane*8 the 8 qh bytes are contiguous at 16 + (lane&3)*8. */
kernel void matmul_nt_Q5K_F(device const uint8_t *w [[buffer(0)]],
                            device const float *x [[buffer(1)]],
                            device float *y [[buffer(2)]],
                            device const float *tables [[buffer(3)]],
                            constant struct MatmulParams &p [[buffer(4)]],
                            uint tid [[thread_position_in_threadgroup]],
                            uint tg [[threadgroup_position_in_grid]]) {
    threadgroup float sh[256];
    uint64_t rows  = u2_to_u64(p.rows);
    uint64_t cols  = u2_to_u64(p.cols);
    uint64_t tiles = (rows + 7) / 8;
    uint64_t b     = (uint64_t)tg / tiles;
    uint64_t tile  = (uint64_t)tg % tiles;
    uint simd = tid >> 5;
    uint lane = tid & 31;
    uint64_t r = tile * 8 + simd;
    float sum = 0.0f;
    if (r < rows) {
        device const float *xr = x + b * cols;
        uint64_t i0 = r * cols, i1 = i0 + cols;
        uint64_t bs = (i0 + 255) >> 8, be = i1 >> 8;
        uint64_t hend = (bs * 256 < i1) ? bs * 256 : i1;
        for (uint64_t c = lane; c < hend - i0; c += 32)
            sum += dequant_Q5_K(w, i0 + c, tables) * xr[c];
        for (uint64_t bi = bs; bi < be; bi++) {
            device const uint8_t *blk = w + bi * 176;
            float d    = f16_to_f32(ld_u16(blk));
            float dmin = f16_to_f32(ld_u16(blk + 2));
            uint32_t o0 = lane * 8;
            uint8_t sc, mn;
            q4k_scale_min(blk + 4, o0 >> 5, &sc, &mn);
            float s = d * (float)sc, m = dmin * (float)mn;
            uint32_t qoff = 48 + (lane >> 3) * 32 + ((lane & 3) * 8);
            uint32_t hoff = 16 + ((lane & 3) * 8);
            uint32_t w0 = ld_u32(blk + qoff), w1 = ld_u32(blk + qoff + 4);
            uint32_t h0 = ld_u32(blk + hoff), h1 = ld_u32(blk + hoff + 4);
            uint32_t nb = (o0 >> 5) & 1;
            uint32_t msk = nb ? 0xF0F0F0F0u : 0x0F0F0F0Fu;
            uint32_t a0 = (w0 & msk) >> (nb ? 4 : 0);
            uint32_t a1 = (w1 & msk) >> (nb ? 4 : 0);
            uint32_t hb = 1u << (o0 >> 5);          /* high-bit position   */
            uint64_t xc = (bi * 256 - i0) + (uint64_t)lane * 8;
            device const float4 *xv = (device const float4 *)(xr + xc);
            float4 v0 = xv[0], v1 = xv[1];
            float q0 = (float)((a0 & 0xFF)        | (((h0       ) & hb) ? 16 : 0));
            float q1 = (float)(((a0 >> 8) & 0xFF)  | (((h0 >> 8 ) & hb) ? 16 : 0));
            float q2 = (float)(((a0 >> 16) & 0xFF) | (((h0 >> 16) & hb) ? 16 : 0));
            float q3 = (float)(((a0 >> 24) & 0xFF) | (((h0 >> 24) & hb) ? 16 : 0));
            float q4 = (float)((a1 & 0xFF)        | (((h1       ) & hb) ? 16 : 0));
            float q5 = (float)(((a1 >> 8) & 0xFF)  | (((h1 >> 8 ) & hb) ? 16 : 0));
            float q6 = (float)(((a1 >> 16) & 0xFF) | (((h1 >> 16) & hb) ? 16 : 0));
            float q7 = (float)(((a1 >> 24) & 0xFF) | (((h1 >> 24) & hb) ? 16 : 0));
            float sq = q0 * v0.x + q1 * v0.y + q2 * v0.z + q3 * v0.w +
                       q4 * v1.x + q5 * v1.y + q6 * v1.z + q7 * v1.w;
            float sx = (v0.x + v0.y) + (v0.z + v0.w) + (v1.x + v1.y) + (v1.z + v1.w);
            sum += s * sq - m * sx;
        }
        uint64_t tstart = (be * 256 > i0) ? be * 256 : i0;
        if (tstart < hend) tstart = hend;
        for (uint64_t c = (tstart - i0) + lane; c < cols; c += 32)
            sum += dequant_Q5_K(w, i0 + c, tables) * xr[c];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (lane == 0 && r < rows) {
        float s = 0.0f;
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];
        y[b * rows + r] = s;
    }
}

/* Q6_K (210 = 128 ql + 64 qh + 16 scales + 2 d).
 * For o0 = lane*8: sc = int8 at 192+(o0>>4), half = o0>>7, which = (o0&127)>>5
 * and l = o0&31 are all constant over the 8 elements, so ql bytes are
 * 8-contiguous at (half<<6)+((which&1)<<5)+l and qh at 128+(half<<5)+l.
 * value = d*sc*(q - 32) with q = lo|(hi<<4). */
kernel void matmul_nt_Q6K_F(device const uint8_t *w [[buffer(0)]],
                            device const float *x [[buffer(1)]],
                            device float *y [[buffer(2)]],
                            device const float *tables [[buffer(3)]],
                            constant struct MatmulParams &p [[buffer(4)]],
                            uint tid [[thread_position_in_threadgroup]],
                            uint tg [[threadgroup_position_in_grid]]) {
    threadgroup float sh[256];
    uint64_t rows  = u2_to_u64(p.rows);
    uint64_t cols  = u2_to_u64(p.cols);
    uint64_t tiles = (rows + 7) / 8;
    uint64_t b     = (uint64_t)tg / tiles;
    uint64_t tile  = (uint64_t)tg % tiles;
    uint simd = tid >> 5;
    uint lane = tid & 31;
    uint64_t r = tile * 8 + simd;
    float sum = 0.0f;
    if (r < rows) {
        device const float *xr = x + b * cols;
        uint64_t i0 = r * cols, i1 = i0 + cols;
        uint64_t bs = (i0 + 255) >> 8, be = i1 >> 8;
        uint64_t hend = (bs * 256 < i1) ? bs * 256 : i1;
        for (uint64_t c = lane; c < hend - i0; c += 32)
            sum += dequant_Q6_K(w, i0 + c, tables) * xr[c];
        for (uint64_t bi = bs; bi < be; bi++) {
            device const uint8_t *blk = w + bi * 210;
            float d  = f16_to_f32(ld_u16(blk + 208));
            uint32_t o0 = lane * 8;
            int32_t sci = (int8_t)blk[192 + (o0 >> 4)];
            float s = d * (float)sci;
            uint32_t hl    = o0 & 127;
            uint32_t which = hl >> 5;
            uint32_t l     = hl & 31;
            uint32_t halfsel = o0 >> 7;
            uint32_t lof   = (halfsel << 6) + ((which & 1) << 5) + l;
            uint32_t hif   = 128 + (halfsel << 5) + l;
            uint32_t l0 = ld_u32(blk + lof), l1 = ld_u32(blk + lof + 4);
            uint32_t h0 = ld_u32(blk + hif), h1 = ld_u32(blk + hif + 4);
            uint32_t lm = (which >= 2) ? 0xF0F0F0F0u : 0x0F0F0F0Fu;
            uint32_t ls = (which >= 2) ? 4 : 0;
            uint32_t a0 = (l0 & lm) >> ls, a1 = (l1 & lm) >> ls;
            uint32_t hs = which * 2, hm = 0x3u << hs;
            uint64_t xc = (bi * 256 - i0) + (uint64_t)lane * 8;
            device const float4 *xv = (device const float4 *)(xr + xc);
            float4 v0 = xv[0], v1 = xv[1];
            float q0 = (float)((int32_t)(((a0 & 0xFF)        | (((h0       ) & hm) >> hs) << 4)) - 32);
            float q1 = (float)((int32_t)((((a0 >> 8) & 0xFF)  | (((h0 >> 8 ) & hm) >> hs) << 4)) - 32);
            float q2 = (float)((int32_t)((((a0 >> 16) & 0xFF) | (((h0 >> 16) & hm) >> hs) << 4)) - 32);
            float q3 = (float)((int32_t)((((a0 >> 24) & 0xFF) | (((h0 >> 24) & hm) >> hs) << 4)) - 32);
            float q4 = (float)((int32_t)(((a1 & 0xFF)        | (((h1       ) & hm) >> hs) << 4)) - 32);
            float q5 = (float)((int32_t)((((a1 >> 8) & 0xFF)  | (((h1 >> 8 ) & hm) >> hs) << 4)) - 32);
            float q6 = (float)((int32_t)((((a1 >> 16) & 0xFF) | (((h1 >> 16) & hm) >> hs) << 4)) - 32);
            float q7 = (float)((int32_t)((((a1 >> 24) & 0xFF) | (((h1 >> 24) & hm) >> hs) << 4)) - 32);
            float sq = q0 * v0.x + q1 * v0.y + q2 * v0.z + q3 * v0.w +
                       q4 * v1.x + q5 * v1.y + q6 * v1.z + q7 * v1.w;
            sum += s * sq;
        }
        uint64_t tstart = (be * 256 > i0) ? be * 256 : i0;
        if (tstart < hend) tstart = hend;
        for (uint64_t c = (tstart - i0) + lane; c < cols; c += 32)
            sum += dequant_Q6_K(w, i0 + c, tables) * xr[c];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (lane == 0 && r < rows) {
        float s = 0.0f;
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];
        y[b * rows + r] = s;
    }
}

/* Q8_K (292 = 4 d + 32 bsums + 256 qs).  Per 16-element group a f16
 * bsum; for o0 = lane*8 the group index o0>>4 is constant over the 8
 * elements and the 8 int8 codes are contiguous at 36+o0. */
kernel void matmul_nt_Q8K_F(device const uint8_t *w [[buffer(0)]],
                            device const float *x [[buffer(1)]],
                            device float *y [[buffer(2)]],
                            device const float *tables [[buffer(3)]],
                            constant struct MatmulParams &p [[buffer(4)]],
                            uint tid [[thread_position_in_threadgroup]],
                            uint tg [[threadgroup_position_in_grid]]) {
    threadgroup float sh[256];
    uint64_t rows  = u2_to_u64(p.rows);
    uint64_t cols  = u2_to_u64(p.cols);
    uint64_t tiles = (rows + 7) / 8;
    uint64_t b     = (uint64_t)tg / tiles;
    uint64_t tile  = (uint64_t)tg % tiles;
    uint simd = tid >> 5;
    uint lane = tid & 31;
    uint64_t r = tile * 8 + simd;
    float sum = 0.0f;
    if (r < rows) {
        device const float *xr = x + b * cols;
        uint64_t i0 = r * cols, i1 = i0 + cols;
        uint64_t bs = (i0 + 255) >> 8, be = i1 >> 8;
        uint64_t hend = (bs * 256 < i1) ? bs * 256 : i1;
        for (uint64_t c = lane; c < hend - i0; c += 32)
            sum += dequant_Q8_K(w, i0 + c, tables) * xr[c];
        for (uint64_t bi = bs; bi < be; bi++) {
            device const uint8_t *blk = w + bi * 292;
            float d = ld_f32(blk);
            uint32_t o0 = lane * 8;
            float s = d * f16_to_f32(ld_u16(blk + 4 + 2 * (o0 >> 4)));
            uint32_t a0 = ld_u32(blk + 36 + o0), a1 = ld_u32(blk + 40 + o0);
            uint64_t xc = (bi * 256 - i0) + (uint64_t)lane * 8;
            device const float4 *xv = (device const float4 *)(xr + xc);
            float4 v0 = xv[0], v1 = xv[1];
            float sq = (float)(int8_t)(a0 & 0xFF)        * v0.x +
                       (float)(int8_t)((a0 >> 8) & 0xFF)  * v0.y +
                       (float)(int8_t)((a0 >> 16) & 0xFF) * v0.z +
                       (float)(int8_t)((a0 >> 24) & 0xFF) * v0.w +
                       (float)(int8_t)(a1 & 0xFF)        * v1.x +
                       (float)(int8_t)((a1 >> 8) & 0xFF)  * v1.y +
                       (float)(int8_t)((a1 >> 16) & 0xFF) * v1.z +
                       (float)(int8_t)((a1 >> 24) & 0xFF) * v1.w;
            sum += s * sq;
        }
        uint64_t tstart = (be * 256 > i0) ? be * 256 : i0;
        if (tstart < hend) tstart = hend;
        for (uint64_t c = (tstart - i0) + lane; c < cols; c += 32)
            sum += dequant_Q8_K(w, i0 + c, tables) * xr[c];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (lane == 0 && r < rows) {
        float s = 0.0f;
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];
        y[b * rows + r] = s;
    }
}

/* Q3_K (110 = 32 hmask + 64 qs + 8 sc_low + 4 sc_high + 2 d).
 * For o0 = lane*8: s = o0>>4, g = o0>>7, pr = (o0>>5)&3 are constant,
 * bc = o0&31, so qs bytes are 8-contiguous at 32+g*32+bc and the hmask
 * bytes at o0&31.  value = d*sc*(q-4) with q = lo|(hi<<2), sc = raw-32. */
kernel void matmul_nt_Q3K_F(device const uint8_t *w [[buffer(0)]],
                            device const float *x [[buffer(1)]],
                            device float *y [[buffer(2)]],
                            device const float *tables [[buffer(3)]],
                            constant struct MatmulParams &p [[buffer(4)]],
                            uint tid [[thread_position_in_threadgroup]],
                            uint tg [[threadgroup_position_in_grid]]) {
    threadgroup float sh[256];
    uint64_t rows  = u2_to_u64(p.rows);
    uint64_t cols  = u2_to_u64(p.cols);
    uint64_t tiles = (rows + 7) / 8;
    uint64_t b     = (uint64_t)tg / tiles;
    uint64_t tile  = (uint64_t)tg % tiles;
    uint simd = tid >> 5;
    uint lane = tid & 31;
    uint64_t r = tile * 8 + simd;
    float sum = 0.0f;
    if (r < rows) {
        device const float *xr = x + b * cols;
        uint64_t i0 = r * cols, i1 = i0 + cols;
        uint64_t bs = (i0 + 255) >> 8, be = i1 >> 8;
        uint64_t hend = (bs * 256 < i1) ? bs * 256 : i1;
        for (uint64_t c = lane; c < hend - i0; c += 32)
            sum += dequant_Q3_K(w, i0 + c, tables) * xr[c];
        for (uint64_t bi = bs; bi < be; bi++) {
            device const uint8_t *blk = w + bi * 110;
            float d = f16_to_f32(ld_u16(blk + 108));
            uint32_t o0 = lane * 8;
            uint32_t s  = o0 >> 4;
            uint32_t sc_low  = (blk[96 + (s & 7)]  >> (s >= 8 ? 4 : 0)) & 0xF;
            uint32_t sc_high = (blk[104 + (s & 3)] >> ((s >> 2) * 2)) & 0x3;
            int32_t sci = (int32_t)(sc_low | (sc_high << 4)) - 32;
            float s3 = d * (float)sci;
            uint32_t g  = o0 >> 7, pr = (o0 >> 5) & 3, bc = o0 & 31;
            uint32_t qf = 32 + g * 32 + bc, hf = bc;
            uint32_t q0 = ld_u32(blk + qf), q1 = ld_u32(blk + qf + 4);
            uint32_t h0 = ld_u32(blk + hf), h1 = ld_u32(blk + hf + 4);
            uint32_t lm = 0x03030303u << (pr * 2);
            uint32_t ls = pr * 2;
            uint32_t a0 = (q0 & lm) >> ls, a1 = (q1 & lm) >> ls;
            uint32_t hb = 1u << (o0 >> 5);
            uint64_t xc = (bi * 256 - i0) + (uint64_t)lane * 8;
            device const float4 *xv = (device const float4 *)(xr + xc);
            float4 v0 = xv[0], v1 = xv[1];
            float c0 = (float)((int32_t)(((a0 & 0xFF)        | (((h0       ) & hb) ? 4 : 0)) - 4));
            float c1 = (float)((int32_t)((((a0 >> 8) & 0xFF)  | (((h0 >> 8 ) & hb) ? 4 : 0)) - 4));
            float c2 = (float)((int32_t)((((a0 >> 16) & 0xFF) | (((h0 >> 16) & hb) ? 4 : 0)) - 4));
            float c3 = (float)((int32_t)((((a0 >> 24) & 0xFF) | (((h0 >> 24) & hb) ? 4 : 0)) - 4));
            float c4 = (float)((int32_t)(((a1 & 0xFF)        | (((h1       ) & hb) ? 4 : 0)) - 4));
            float c5 = (float)((int32_t)((((a1 >> 8) & 0xFF)  | (((h1 >> 8 ) & hb) ? 4 : 0)) - 4));
            float c6 = (float)((int32_t)((((a1 >> 16) & 0xFF) | (((h1 >> 16) & hb) ? 4 : 0)) - 4));
            float c7 = (float)((int32_t)((((a1 >> 24) & 0xFF) | (((h1 >> 24) & hb) ? 4 : 0)) - 4));
            float sq = c0 * v0.x + c1 * v0.y + c2 * v0.z + c3 * v0.w +
                       c4 * v1.x + c5 * v1.y + c6 * v1.z + c7 * v1.w;
            sum += s3 * sq;
        }
        uint64_t tstart = (be * 256 > i0) ? be * 256 : i0;
        if (tstart < hend) tstart = hend;
        for (uint64_t c = (tstart - i0) + lane; c < cols; c += 32)
            sum += dequant_Q3_K(w, i0 + c, tables) * xr[c];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (lane == 0 && r < rows) {
        float s = 0.0f;
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];
        y[b * rows + r] = s;
    }
}

/* Q2_K (84 = 64 qs + 8 scales + 8 pad + 2 d + 2 mn per this decoder).
 * For o0 = lane*8: sb = o0>>4 constant -> one 4-bit scale; the 8 two-bit
 * codes live in 2 contiguous bytes at o0>>2 and the 8 high bits in ONE
 * byte at o0>>3 (= lane) at bit positions t = 0..7. */
kernel void matmul_nt_Q2K_F(device const uint8_t *w [[buffer(0)]],
                            device const float *x [[buffer(1)]],
                            device float *y [[buffer(2)]],
                            device const float *tables [[buffer(3)]],
                            constant struct MatmulParams &p [[buffer(4)]],
                            uint tid [[thread_position_in_threadgroup]],
                            uint tg [[threadgroup_position_in_grid]]) {
    threadgroup float sh[256];
    uint64_t rows  = u2_to_u64(p.rows);
    uint64_t cols  = u2_to_u64(p.cols);
    uint64_t tiles = (rows + 7) / 8;
    uint64_t b     = (uint64_t)tg / tiles;
    uint64_t tile  = (uint64_t)tg % tiles;
    uint simd = tid >> 5;
    uint lane = tid & 31;
    uint64_t r = tile * 8 + simd;
    float sum = 0.0f;
    if (r < rows) {
        device const float *xr = x + b * cols;
        uint64_t i0 = r * cols, i1 = i0 + cols;
        uint64_t bs = (i0 + 255) >> 8, be = i1 >> 8;
        uint64_t hend = (bs * 256 < i1) ? bs * 256 : i1;
        for (uint64_t c = lane; c < hend - i0; c += 32)
            sum += dequant_Q2_K(w, i0 + c, tables) * xr[c];
        for (uint64_t bi = bs; bi < be; bi++) {
            device const uint8_t *blk = w + bi * 84;
            float d  = f16_to_f32(ld_u16(blk + 80));
            float mn = f16_to_f32(ld_u16(blk + 82));
            uint32_t o0 = lane * 8;
            uint32_t sb = o0 >> 4;
            uint32_t scr = blk[64 + (sb >> 1)];
            if (sb & 1) scr >>= 4; else scr &= 0xF;
            float s = d * (float)(int32_t)scr;
            uint32_t q0 = ld_u32(blk + (o0 >> 2));      /* 4 codes in lo16 */
            uint32_t hb = blk[lane];                     /* 8 high bits     */
            uint64_t xc = (bi * 256 - i0) + (uint64_t)lane * 8;
            device const float4 *xv = (device const float4 *)(xr + xc);
            float4 v0 = xv[0], v1 = xv[1];
            float c0 = (float)((int32_t)((q0       ) & 0x3) - (int32_t)(((hb >> 0) & 1) * 4));
            float c1 = (float)((int32_t)((q0 >> 2) & 0x3) - (int32_t)(((hb >> 1) & 1) * 4));
            float c2 = (float)((int32_t)((q0 >> 4) & 0x3) - (int32_t)(((hb >> 2) & 1) * 4));
            float c3 = (float)((int32_t)((q0 >> 6) & 0x3) - (int32_t)(((hb >> 3) & 1) * 4));
            float c4 = (float)((int32_t)((q0 >> 8) & 0x3) - (int32_t)(((hb >> 4) & 1) * 4));
            float c5 = (float)((int32_t)((q0 >> 10) & 0x3) - (int32_t)(((hb >> 5) & 1) * 4));
            float c6 = (float)((int32_t)((q0 >> 12) & 0x3) - (int32_t)(((hb >> 6) & 1) * 4));
            float c7 = (float)((int32_t)((q0 >> 14) & 0x3) - (int32_t)(((hb >> 7) & 1) * 4));
            float sq = c0 * v0.x + c1 * v0.y + c2 * v0.z + c3 * v0.w +
                       c4 * v1.x + c5 * v1.y + c6 * v1.z + c7 * v1.w;
            float sx = (v0.x + v0.y) + (v0.z + v0.w) + (v1.x + v1.y) + (v1.z + v1.w);
            sum += s * sq - mn * sx;
        }
        uint64_t tstart = (be * 256 > i0) ? be * 256 : i0;
        if (tstart < hend) tstart = hend;
        for (uint64_t c = (tstart - i0) + lane; c < cols; c += 32)
            sum += dequant_Q2_K(w, i0 + c, tables) * xr[c];
    }
    sh[tid] = sum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (lane == 0 && r < rows) {
        float s = 0.0f;
        for (uint k = 0; k < 32; k++) s += sh[simd * 32 + k];
        y[b * rows + r] = s;
    }
}

/* ================================================================
 * Graph-op kernels (device-resident path)
 *
 * The host passes per-op scalars as a flat little-endian uint32 array
 * in buffer `a` (64-bit values occupy two consecutive words).  All
 * grids are 1-D: the host flattens multi-dimensional grids and the
 * kernels decompose the threadgroup index accordingly.  Every
 * reduction uses OP_TPTG threads (the host always dispatches 256).
 * ================================================================ */

#define OP_TPTG 256

static inline uint64_t op_u64(device const uint32_t *a, uint i) {
    return (uint64_t)a[i] | ((uint64_t)a[i + 1] << 32);
}
static inline float op_f32(device const uint32_t *a, uint i) {
    union { uint32_t u; float f; } v = { a[i] };
    return v.f;
}
static inline float op_neg_inf(void) {
    return u32_as_f32(0xff800000u);
}

static inline float tg_sum(threadgroup float *sh, float v, uint tid) {
    sh[tid] = v;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint s = OP_TPTG >> 1; s > 0; s >>= 1) {
        if (tid < s) sh[tid] += sh[tid + s];
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    float r = sh[0];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    return r;
}
static inline float tg_max(threadgroup float *sh, float v, uint tid) {
    sh[tid] = v;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint s = OP_TPTG >> 1; s > 0; s >>= 1) {
        if (tid < s) sh[tid] = fmax(sh[tid], sh[tid + s]);
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    float r = sh[0];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    return r;
}

/* OP_RMS_NORM: args [od, base, wn, eps(f32)]; grid = r. */
kernel void op_rms_norm(device const float *src [[buffer(0)]],
                        device float *dst [[buffer(1)]],
                        device const float *w [[buffer(2)]],
                        device const uint32_t *a [[buffer(3)]],
                        uint tid [[thread_position_in_threadgroup]],
                        uint tg [[threadgroup_position_in_grid]],
                        uint tptg [[threads_per_threadgroup]]) {
    threadgroup float sh[OP_TPTG];
    uint od = a[0], base = a[1], wn = a[2];
    float eps = op_f32(a, 3);
    device const float *x = src + ((uint64_t)base + tg) * od;
    device float *d = dst + (uint64_t)tg * od;
    float ss = 0.0f;
    for (uint i = tid; i < od; i += tptg) ss += x[i] * x[i];
    ss = tg_sum(sh, ss, tid);
    float scale = 1.0f / sqrt(ss / (float)od + eps);
    for (uint i = tid; i < od; i += tptg) {
        float wi = (i < wn) ? w[i] : 0.0f;
        d[i] = x[i] * scale * wi;
    }
}

/* OP_RMS_NORM_HEADS: args [nh, hd, is, os, od, base, eps(f32)];
 * grid = r * nh with tg = p*nh + h. */
kernel void op_rms_norm_heads(device const float *src [[buffer(0)]],
                              device float *dst [[buffer(1)]],
                              device const float *nw [[buffer(2)]],
                              device const uint32_t *a [[buffer(3)]],
                              uint tid [[thread_position_in_threadgroup]],
                              uint tg [[threadgroup_position_in_grid]],
                              uint tptg [[threads_per_threadgroup]]) {
    threadgroup float sh[OP_TPTG];
    uint nh = a[0], hd = a[1], is = a[2], os = a[3], od = a[4], base = a[5];
    float eps = op_f32(a, 6);
    uint h = tg % nh, p = tg / nh;
    device const float *sp = src + (((uint64_t)base + p) * nh + h) * is;
    device float *dp = dst + (uint64_t)p * od + (uint64_t)h * os;
    float ss = 0.0f;
    for (uint d = tid; d < hd; d += tptg) ss += sp[d] * sp[d];
    ss = tg_sum(sh, ss, tid);
    float scale = 1.0f / sqrt(ss / (float)hd + eps);
    for (uint d = tid; d < hd; d += tptg) dp[d] = sp[d] * scale * nw[d];
}

/* OP_BIAS: args [nb, od, base, total(2)]; grid covers total. */
kernel void op_bias(device const float *src [[buffer(0)]],
                    device float *dst [[buffer(1)]],
                    device const float *bw [[buffer(2)]],
                    device const uint32_t *a [[buffer(3)]],
                    uint gid [[thread_position_in_grid]],
                    uint tptg [[threads_per_threadgroup]],
                    uint ntg [[threadgroups_per_grid]]) {
    uint nb = a[0], od = a[1], base = a[2];
    uint64_t total = op_u64(a, 3);
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t idx = gid; idx < total; idx += stride) {
        uint p = (uint)(idx / od), j = (uint)(idx % od);
        float b = (j < nb) ? bw[j] : 0.0f;
        dst[idx] = src[((uint64_t)base + p) * od + j] + b;
    }
}

/* OP_ADD / OP_MUL: args [od, base, total(2), add]; grid covers total. */
kernel void op_binary(device const float *A [[buffer(0)]],
                      device const float *B [[buffer(1)]],
                      device float *dst [[buffer(2)]],
                      device const uint32_t *a [[buffer(3)]],
                      uint gid [[thread_position_in_grid]],
                      uint tptg [[threads_per_threadgroup]],
                      uint ntg [[threadgroups_per_grid]]) {
    uint od = a[0], base = a[1], add = a[4];
    uint64_t total = op_u64(a, 2);
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t idx = gid; idx < total; idx += stride) {
        uint p = (uint)(idx / od), j = (uint)(idx % od);
        uint64_t off = ((uint64_t)base + p) * od + j;
        dst[idx] = add ? (A[off] + B[off]) : (A[off] * B[off]);
    }
}

/* OP_SILU: args [od, base, total(2)]; grid covers total. */
kernel void op_silu(device const float *src [[buffer(0)]],
                    device float *dst [[buffer(1)]],
                    device const uint32_t *a [[buffer(2)]],
                    uint gid [[thread_position_in_grid]],
                    uint tptg [[threads_per_threadgroup]],
                    uint ntg [[threadgroups_per_grid]]) {
    uint od = a[0], base = a[1];
    uint64_t total = op_u64(a, 2);
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t idx = gid; idx < total; idx += stride) {
        uint p = (uint)(idx / od), j = (uint)(idx % od);
        float v = src[((uint64_t)base + p) * od + j];
        dst[idx] = v / (1.0f + exp(-v));
    }
}

/* OP_SOFTMAX: args [od, base]; one threadgroup per row. */
kernel void op_softmax(device const float *src [[buffer(0)]],
                       device float *dst [[buffer(1)]],
                       device const uint32_t *a [[buffer(2)]],
                       uint tid [[thread_position_in_threadgroup]],
                       uint tg [[threadgroup_position_in_grid]],
                       uint tptg [[threads_per_threadgroup]]) {
    threadgroup float sh[OP_TPTG];
    uint od = a[0], base = a[1];
    device const float *x = src + ((uint64_t)base + tg) * od;
    device float *d = dst + (uint64_t)tg * od;
    float mx = op_neg_inf();
    for (uint i = tid; i < od; i += tptg) mx = fmax(mx, x[i]);
    mx = tg_max(sh, mx, tid);
    float sum = 0.0f;
    for (uint i = tid; i < od; i += tptg) {
        float e = exp(x[i] - mx);
        d[i] = e;
        sum += e;
    }
    sum = tg_sum(sh, sum, tid);
    for (uint i = tid; i < od; i += tptg) d[i] /= sum;
}

/* OP_ROPE_NEOX: args [theta(f32), nh, hdim, rdim, od, base, pos, total(2)];
 * one thread per (row, head, i < hdim/2). */
kernel void op_rope_neox(device const float *src [[buffer(0)]],
                         device float *dst [[buffer(1)]],
                         device const uint32_t *a [[buffer(2)]],
                         uint gid [[thread_position_in_grid]],
                         uint tptg [[threads_per_threadgroup]],
                         uint ntg [[threadgroups_per_grid]]) {
    float theta_base = op_f32(a, 0);
    uint nh = a[1], hdim = a[2], rdim = a[3], od = a[4], base = a[5], pos = a[6];
    uint64_t total = op_u64(a, 7);
    uint64_t stride = (uint64_t)ntg * tptg;
    uint hh = hdim / 2, npair = rdim / 2;
    for (uint64_t idx = gid; idx < total; idx += stride) {
        uint p = (uint)(idx / (nh * hh));
        uint rem = (uint)(idx % (nh * hh));
        uint h = rem / hh, i = rem % hh;
        uint abspos = pos + base + p;
        device const float *sp = src + ((uint64_t)base + p) * od + (uint64_t)h * hdim;
        device float *dp = dst + (uint64_t)p * od + (uint64_t)h * hdim;
        float a0 = sp[i], b0 = sp[i + hh];
        if (i < npair) {
            float t = 1.0f / pow(theta_base, (float)(2 * i) / (float)rdim);
            float c = cos((float)abspos * t);
            float s = sin((float)abspos * t);
            dp[i] = a0 * c - b0 * s;
            dp[i + hh] = a0 * s + b0 * c;
        } else {
            dp[i] = a0;
            dp[i + hh] = b0;
        }
    }
}

/* OP_SIGMOID_GATE: args [hd, od, gate_stride, base, total(2)]; grid covers total. */
kernel void op_sigmoid_gate(device const float *A [[buffer(0)]],
                            device const float *G [[buffer(1)]],
                            device float *dst [[buffer(2)]],
                            device const uint32_t *a [[buffer(3)]],
                            uint gid [[thread_position_in_grid]],
                            uint tptg [[threads_per_threadgroup]],
                            uint ntg [[threadgroups_per_grid]]) {
    uint hd = a[0], od = a[1], gate_stride = a[2], base = a[3];
    uint64_t total = op_u64(a, 4);
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t idx = gid; idx < total; idx += stride) {
        uint p = (uint)(idx / od), j = (uint)(idx % od);
        uint h = j / hd, d = j % hd;
        float av = A[((uint64_t)base + p) * od + j];
        float gv = G[((uint64_t)base + p) * gate_stride + (uint64_t)h * 2 * hd + hd + d];
        dst[idx] = av / (1.0f + exp(-gv));
    }
}

/* OP_SSM_CONV: args [od, ck, r, base]; one threadgroup, rows sequential. */
kernel void op_ssm_conv(device const float *src [[buffer(0)]],
                        device float *dst [[buffer(1)]],
                        device const float *cw [[buffer(2)]],
                        device float *state [[buffer(3)]],
                        device const uint32_t *a [[buffer(4)]],
                        uint tid [[thread_position_in_threadgroup]],
                        uint tptg [[threads_per_threadgroup]]) {
    uint od = a[0], ck = a[1], r = a[2], base = a[3];
    for (uint p = 0; p < r; p++) {
        device const float *sp = src + ((uint64_t)base + p) * od;
        device float *dp = dst + (uint64_t)p * od;
        for (uint c = tid; c < od; c += tptg) {
            float sum = 0.0f;
            for (uint k = 0; k < ck; k++) {
                float x = (k == ck - 1) ? sp[c] : state[(uint64_t)k * od + c];
                sum += x * cw[(uint64_t)c * ck + k];
            }
            dp[c] = sum;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint s = 0; s + 1 < ck - 1; s++) {
            for (uint c = tid; c < od; c += tptg)
                state[(uint64_t)s * od + c] = state[(uint64_t)(s + 1) * od + c];
            threadgroup_barrier(mem_flags::mem_threadgroup);
        }
        if (ck > 1) {
            uint tail = (ck - 2) * od;
            for (uint c = tid; c < od; c += tptg) state[(uint64_t)tail + c] = sp[c];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
}

/* OP_SSM_DELTA: args [n_v, n_k, hd, key_dim, od, base, r, has_nw, eps(f32)];
 * grid = n_v; rows looped inside (state advances sequentially per head).
 * hd must be <= OP_TPTG. */
kernel void op_ssm_delta(device const float *fused [[buffer(0)]],
                         device const float *alpha [[buffer(1)]],
                         device const float *beta [[buffer(2)]],
                         device const float *a_log [[buffer(3)]],
                         device const float *dt_bias [[buffer(4)]],
                         device const float *nw [[buffer(5)]],
                         device float *state [[buffer(6)]],
                         device float *dst [[buffer(7)]],
                         device const uint32_t *a [[buffer(8)]],
                         uint tid [[thread_position_in_threadgroup]],
                         uint grp [[threadgroup_position_in_grid]],
                         uint tptg [[threads_per_threadgroup]]) {
    threadgroup float qsh[OP_TPTG], ksh[OP_TPTG], red[OP_TPTG];
    uint n_v = a[0], n_k = a[1], hd = a[2], key_dim = a[3], od = a[4];
    uint base = a[5], r = a[6]; uint has_nw = a[7];
    float eps = op_f32(a, 8);
    uint kh = grp % n_k;
    uint64_t d2 = (uint64_t)hd * hd;
    uint64_t fstride = 2 * (uint64_t)key_dim + (uint64_t)n_v * hd;
    for (uint p = 0; p < r; p++) {
        device const float *fr = fused + ((uint64_t)base + p) * fstride;
        device const float *ar = alpha + ((uint64_t)base + p) * n_v;
        device const float *br = beta + ((uint64_t)base + p) * n_v;
        device float *Sg = state + (uint64_t)grp * d2;
        float z = ar[grp] + dt_bias[grp];
        float g = exp(a_log[grp] * ((z > 20.0f) ? z : log(1.0f + exp(z))));
        float b = 1.0f / (1.0f + exp(-br[grp]));
        for (uint64_t i = tid; i < d2; i += tptg) Sg[i] *= g;
        threadgroup_barrier(mem_flags::mem_threadgroup);

        device const float *Qg = fr + (uint64_t)kh * hd;
        device const float *Kg = fr + key_dim + (uint64_t)kh * hd;
        device const float *Vg = fr + 2 * (uint64_t)key_dim + (uint64_t)grp * hd;
        float vq = 0.0f, vk = 0.0f, vv = 0.0f;
        if (tid < hd) { vq = Qg[tid]; vk = Kg[tid]; vv = Vg[tid]; qsh[tid] = vq; ksh[tid] = vk; }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float ss = tg_sum(red, (tid < hd) ? vq * vq : 0.0f, tid);
        vq *= 1.0f / sqrt(ss + eps);
        ss = tg_sum(red, (tid < hd) ? vk * vk : 0.0f, tid);
        vk *= 1.0f / sqrt(ss + eps);
        vq *= 1.0f / sqrt((float)hd);
        if (tid < hd) { qsh[tid] = vq; ksh[tid] = vk; }
        threadgroup_barrier(mem_flags::mem_threadgroup);

        float out = 0.0f;
        if (tid < hd) {
            float mem = 0.0f;
            for (uint i = 0; i < hd; i++) mem += Sg[(uint64_t)i * hd + tid] * ksh[i];
            float delta = (vv - mem) * b;
            for (uint i = 0; i < hd; i++) {
                device float *col = Sg + (uint64_t)i * hd + tid;
                *col += ksh[i] * delta;
                out += *col * qsh[i];
            }
        }
        if (has_nw) {
            ss = tg_sum(red, (tid < hd) ? out * out : 0.0f, tid);
            if (tid < hd)
                dst[(uint64_t)p * od + (uint64_t)grp * hd + tid] =
                    out * (1.0f / sqrt(ss / (float)hd + eps)) * nw[tid];
        } else if (tid < hd) {
            dst[(uint64_t)p * od + (uint64_t)grp * hd + tid] = out;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
}

/* OP_ATTN phase 1 — write the batch K/V rows into the device cache.
 * args [n_kv, khd, kv_dim, hs(2), pos, total(2)]; grid covers total. */
kernel void op_kv_write(device float *ck [[buffer(0)]],
                        device float *cv [[buffer(1)]],
                        device const float *kd [[buffer(2)]],
                        device const float *vd [[buffer(3)]],
                        device const uint32_t *a [[buffer(4)]],
                        uint gid [[thread_position_in_grid]],
                        uint tptg [[threads_per_threadgroup]],
                        uint ntg [[threadgroups_per_grid]]) {
    uint n_kv = a[0], khd = a[1], kv_dim = a[2];
    uint64_t hs = op_u64(a, 3);
    uint pos = a[5];
    uint64_t total = op_u64(a, 6);
    uint64_t stride = (uint64_t)ntg * tptg;
    for (uint64_t idx = gid; idx < total; idx += stride) {
        uint i = (uint)(idx / ((uint64_t)n_kv * khd));
        uint rem = (uint)(idx % ((uint64_t)n_kv * khd));
        uint h = rem / khd, d = rem % khd;
        ck[(uint64_t)h * hs + (uint64_t)(pos + i) * khd + d] =
            kd[(uint64_t)i * kv_dim + (uint64_t)h * khd + d];
        cv[(uint64_t)h * hs + (uint64_t)(pos + i) * khd + d] =
            vd[(uint64_t)i * kv_dim + (uint64_t)h * khd + d];
    }
}

/* OP_ATTN phase 2 — one threadgroup per (query row, head).  Streaming
 * softmax so the score tile stays in threadgroup memory.
 * args [n_head, gqa, hd, khd, q_dim, hs(2), pos, scale(f32)];
 * grid = r * n_head with tg = qi*n_head + h.  khd <= OP_TPTG. */
kernel void op_attn(device const float *qd [[buffer(0)]],
                    device const float *ck [[buffer(1)]],
                    device const float *cv [[buffer(2)]],
                    device float *dst [[buffer(3)]],
                    device const uint32_t *a [[buffer(4)]],
                    uint tid [[thread_position_in_threadgroup]],
                    uint tg [[threadgroup_position_in_grid]],
                    uint tptg [[threads_per_threadgroup]]) {
    threadgroup float acc[OP_TPTG], pv[OP_TPTG], red[OP_TPTG];
    threadgroup float msm[1], lsm[1];
    uint n_head = a[0], gqa = a[1], hd = a[2], khd = a[3], q_dim = a[4];
    uint64_t hs = op_u64(a, 5);
    uint pos = a[7];
    float scale = op_f32(a, 8);
    uint h = tg % n_head, qi = tg / n_head;
    device const float *qh = qd + (uint64_t)qi * q_dim + (uint64_t)h * hd;
    device const float *Kb = ck + (uint64_t)(h / gqa) * hs;
    device const float *Vb = cv + (uint64_t)(h / gqa) * hs;
    uint n_keys = pos + qi + 1;

    for (uint d = tid; d < khd; d += tptg) acc[d] = 0.0f;
    if (tid == 0) { msm[0] = op_neg_inf(); lsm[0] = 0.0f; }
    threadgroup_barrier(mem_flags::mem_threadgroup);

    for (uint t0 = 0; t0 < n_keys; t0 += tptg) {
        threadgroup_barrier(mem_flags::mem_threadgroup);
        float mval = msm[0];
        uint tile = min(tptg, n_keys - t0);
        float s = op_neg_inf();
        if (tid < tile) {
            device const float *kt = Kb + (uint64_t)(t0 + tid) * khd;
            float dot = 0.0f;
            for (uint d = 0; d < khd; d++) dot += qh[d] * kt[d];
            s = dot * scale;
        }
        float tmax = tg_max(red, s, tid);
        float new_m = fmax(mval, tmax);
        pv[tid] = (tid < tile) ? exp(s - new_m) : 0.0f;
        float factor = exp(mval - new_m);
        float tsum = tg_sum(red, pv[tid], tid);
        if (tid == 0) { lsm[0] = lsm[0] * factor + tsum; msm[0] = new_m; }
        for (uint d = tid; d < khd; d += tptg) {
            float acc2 = acc[d] * factor;
            for (uint t2 = 0; t2 < tile; t2++)
                acc2 += pv[t2] * Vb[(uint64_t)(t0 + t2) * khd + d];
            acc[d] = acc2;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    float l = lsm[0];
    for (uint d = tid; d < khd; d += tptg)
        dst[(uint64_t)qi * q_dim + (uint64_t)h * hd + d] = acc[d] / l;
}

/* OP_EMBED gather: args [type, n_ids, count, base_mul(2), stride(2)];
 * grid covers n_ids * count. */
kernel void op_dequant_gather(device const uint8_t *w [[buffer(0)]],
                              device const uint32_t *ids [[buffer(1)]],
                              device float *out [[buffer(2)]],
                              device const float *tables [[buffer(3)]],
                              device const uint32_t *a [[buffer(4)]],
                              uint gid [[thread_position_in_grid]],
                              uint tptg [[threads_per_threadgroup]],
                              uint ntg [[threadgroups_per_grid]]) {
    uint type = a[0], n_ids = a[1], count = a[2];
    uint64_t base_mul = op_u64(a, 3);
    uint64_t stride = op_u64(a, 5);
    uint64_t gstride = (uint64_t)ntg * tptg;
    for (uint64_t idx = gid; idx < (uint64_t)n_ids * count; idx += gstride) {
        uint p = (uint)(idx / count);
        uint j = (uint)(idx % count);
        out[idx] = dequant_one(type, w, (uint64_t)ids[p] * base_mul + (uint64_t)j * stride, tables);
    }
}
